export const BARANGAYS = [
  'Abo',
  'Alibungbungan',
  'Alumbrado',
  'Balayong',
  'Balimbing',
  'Balinacon',
  'Bambang',
  'Banago',
  'Banca-banca',
  'Bangcuro',
  'Banilad',
  'Bayaquitos',
  'Buboy',
  'Buenavista',
  'Buhanginan',
  'Bukal',
  'Bunga',
  'Cabuyew',
  'Calumpang',
  'Kanluran Kabubuhayan',
  'Kanluran Lazaan',
  'Labangan',
  'Lagulo',
  'Lawaguin',
  'Maiit',
  'Malaya',
  'Malinao',
  'Manaol',
  'Maravilla',
  'Nagcalbang',
  'Oples',
  'Palayan',
  'Palina',
  'Poblacion I (Poblacion)',
  'Poblacion II (Poblacion)',
  'Poblacion III (Poblacion)',
  'Sabang',
  'San Francisco',
  'Santa Lucia',
  'Sibulan',
  'Silangan Ilaya',
  'Silangan Kabubuhayan',
  'Silangan Lazaan',
  'Silangan Napapatid',
  'Sinipian',
  'Sulsuguin',
  'Talahib',
  'Talangan',
  'Taytay',
  'Tipacan',
  'Wakat',
  'Yukos',
] as const;

export type BarangayName = (typeof BARANGAYS)[number];
