import { readFileSync } from 'node:fs';
export const notificationFixtureSql = `
CREATE ROLE anon; CREATE ROLE authenticated;
CREATE TABLE users(id text PRIMARY KEY,role text,status text,"sessionVersion" integer DEFAULT 0);
CREATE TABLE "Profile"("userId" text,city text);
CREATE TABLE id_verification_submissions(id text PRIMARY KEY,user_id text,barangay text,status text,submitted_at timestamp DEFAULT now());
CREATE TABLE "ChallengeSubmission"(id text PRIMARY KEY,"userId" text,status text,created_at timestamp DEFAULT now());
CREATE TABLE event_submissions(id text PRIMARY KEY,user_id text,status text,submitted_at timestamp DEFAULT now());
CREATE TABLE redeem_requests(id text PRIMARY KEY,user_id text,status text,created_at timestamp DEFAULT now());
CREATE TABLE swap_listings(id text PRIMARY KEY,city text,approval_status text,created_at timestamp DEFAULT now());
CREATE TABLE swap_listing_reports(id text PRIMARY KEY,listing_id text,resolved_at timestamp,created_at timestamp DEFAULT now());
CREATE TABLE lessons(id text PRIMARY KEY,title text,is_published boolean,created_at timestamp DEFAULT now());
CREATE TABLE "Challenge"(id text PRIMARY KEY,title text,active boolean,"startDate" timestamp,"endDate" timestamp,"createdAt" timestamp DEFAULT now());
CREATE TABLE "Event"(id text PRIMARY KEY,title text,is_published boolean,barangay text,start_datetime timestamp,end_datetime timestamp,location text,"createdAt" timestamp DEFAULT now(),"updatedAt" timestamp DEFAULT now());
CREATE TABLE announcements(id text PRIMARY KEY,title text,status text,"targetAudience" text,barangays text[],"publishAt" timestamp,"createdAt" timestamp DEFAULT now());
CREATE TABLE notification_deliveries(id text PRIMARY KEY,state text,attempts integer,channel text);
INSERT INTO users(id,role,status) VALUES('admin','admin','active'),('mod-a','moderator','active'),('mod-b','moderator','active'),('resident-a','user','active'),('resident-b','user','active');
INSERT INTO "Profile" VALUES('mod-a','Alibungbungan'),('mod-b','Alumbrado'),('resident-a','Alibungbungan'),('resident-b','Alumbrado');
INSERT INTO id_verification_submissions(id,user_id,barangay,status) VALUES('existing','resident-a','Alibungbungan','pending');
INSERT INTO lessons(id,title,is_published) VALUES('legacy','Existing lesson',true);`;
export const adminNotificationMigration = readFileSync('prisma/migrations/20261005000000_admin_notifications/migration.sql','utf8');
