import { scale, verticalScale, moderateScale, responsiveFontSize } from '../utils/responsive';
import { Platform, StyleSheet } from 'react-native';
import { ecoTheme } from '../../shared/theme/ecoTheme';

export const styles = StyleSheet.create({
  onbGlassCard: {
    borderRadius: moderateScale(32),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    overflow: 'hidden',
    padding: moderateScale(24),
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  onbEcoBadge: {
    width: scale(64),
    height: verticalScale(64),
    borderRadius: moderateScale(32),
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(24),
    shadowColor: ecoTheme.colors.primaryDark,
    shadowOffset: { width: 0, height: verticalScale(8) },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  onbTitle: {
    fontSize: responsiveFontSize(28),
    fontWeight: '800',
    color: '#FFF',
    marginBottom: verticalScale(16),
    textAlign: 'center',
  },
  onbDescription: {
    fontSize: responsiveFontSize(16),
    fontWeight: '500',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    lineHeight: moderateScale(24),
  },
  onbBtn: {
    width: '100%',
    borderRadius: moderateScale(100),
    overflow: 'hidden',
    shadowColor: ecoTheme.colors.primary,
    shadowOffset: { width: 0, height: verticalScale(4) },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  onbGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: verticalScale(18),
    paddingHorizontal: scale(32),
  },
  onbBtnTxt: {
    color: '#FFF',
    fontSize: responsiveFontSize(18),
    fontWeight: '700',
  },
  actionHost: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  actionOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(6, 27, 23, 0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(28),
  },
  actionOverlayCard: {
    width: '100%',
    maxWidth: 320,
    borderRadius: moderateScale(30),
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(28),
    backgroundColor: 'rgba(8, 35, 30, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#0E6D60',
    shadowOpacity: 0.28,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: verticalScale(16) },
    elevation: 16,
  },
  actionOverlayLogoWrap: {
    alignItems: 'center',
    marginBottom: verticalScale(18),
  },
  actionOverlaySpinnerShell: {
    width: scale(132),
    height: verticalScale(132),
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionOverlaySpinnerRing: {
    position: 'absolute',
    width: scale(132),
    height: verticalScale(132),
    borderRadius: moderateScale(999),
    borderWidth: 1.5,
    borderColor: 'rgba(207,255,234,0.22)',
    alignItems: 'center',
  },
  actionOverlaySpinnerDot: {
    width: scale(14),
    height: verticalScale(14),
    borderRadius: moderateScale(999),
    marginTop: verticalScale(9),
    backgroundColor: '#B4FBE0',
    shadowColor: '#B4FBE0',
    shadowOpacity: 0.72,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  actionOverlayLogoCore: {
    width: scale(98),
    height: verticalScale(98),
    borderRadius: moderateScale(999),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 88, 76, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#18A176',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 8,
  },
  actionOverlayTitle: {
    fontSize: responsiveFontSize(20),
    lineHeight: moderateScale(26),
    fontWeight: '900',
    color: '#F2FFF8',
    textAlign: 'center',
  },
  actionOverlayCopy: {
    marginTop: verticalScale(10),
    fontSize: responsiveFontSize(14),
    lineHeight: moderateScale(21),
    color: 'rgba(227,255,244,0.76)',
    textAlign: 'center',
  },
  centeredScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(28),
    overflow: 'hidden',
  },
  bootBackdropOrb: {
    position: 'absolute',
    top: verticalScale(-70),
    right: scale(-35),
    width: '100%', maxWidth: 240,
    height: verticalScale(240),
    borderRadius: moderateScale(120),
    backgroundColor: 'rgba(115, 255, 206, 0.12)',
  },
  bootBackdropOrbSecondary: {
    position: 'absolute',
    bottom: verticalScale(-110),
    left: scale(-70),
    width: '100%', maxWidth: 280,
    height: verticalScale(280),
    borderRadius: moderateScale(140),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  bootOrbitalRing: {
    position: 'absolute',
    width: '100%', maxWidth: 216,
    height: verticalScale(216),
    borderRadius: moderateScale(108),
    borderWidth: 1,
    borderColor: 'rgba(204,255,235,0.22)',
    alignItems: 'center',
  },
  bootOrbitalDot: {
    position: 'absolute',
    top: verticalScale(12),
    width: scale(14),
    height: verticalScale(14),
    borderRadius: moderateScale(7),
    backgroundColor: '#C9FFE8',
    shadowColor: '#9FF7D4',
    shadowOpacity: 0.8,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  bootCenterpiece: {
    width: '100%', maxWidth: 216,
    height: verticalScale(216),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(24),
  },
  bootLogoModern: {
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(18),
    borderRadius: moderateScale(28),
    backgroundColor: 'rgba(4, 27, 21, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#72F1C1',
    shadowOpacity: 0.38,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: verticalScale(16) },
    elevation: 15,
  },
  bootTitleModern: {
    fontSize: responsiveFontSize(24),
    fontWeight: '900',
    color: '#ECFDF5',
    letterSpacing: 0.3,
  },
  bootSubtitleModern: {
    marginTop: verticalScale(10),
    fontSize: responsiveFontSize(15),
    fontWeight: '600',
    color: 'rgba(225,255,245,0.82)',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  bootLoaderChip: {
    marginTop: verticalScale(28),
    minHeight: 46,
    borderRadius: moderateScale(23),
    paddingHorizontal: scale(16),
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  bootLoaderText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '700',
    color: '#E9FFF5',
  },
  landingScreen: {
    flex: 1,
    overflow: 'hidden',
  },
  landingBackdropOrbPrimary: {
    position: 'absolute',
    top: verticalScale(-80),
    right: scale(-50),
    width: '100%', maxWidth: 250,
    height: verticalScale(250),
    borderRadius: moderateScale(125),
    backgroundColor: 'rgba(206, 255, 233, 0.14)',
  },
  landingBackdropOrbSecondary: {
    position: 'absolute',
    bottom: verticalScale(-110),
    left: scale(-60),
    width: '100%', maxWidth: 300,
    height: verticalScale(300),
    borderRadius: moderateScale(150),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  launchBackdropCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(28),
  },
  launchBackdropCore: {
    width: scale(150),
    height: verticalScale(150),
    borderRadius: moderateScale(999),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#93FFD2',
    shadowOpacity: 0.2,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: verticalScale(14) },
    elevation: 12,
  },
  launchBackdropCopy: {
    marginTop: verticalScale(22),
    fontSize: responsiveFontSize(16),
    lineHeight: moderateScale(24),
    fontWeight: '700',
    color: '#F1FFF8',
    textAlign: 'center',
  },
  landingShell: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(28),
  },
  landingContent: {
    borderRadius: moderateScale(38),
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(26),
    backgroundColor: 'rgba(7, 32, 28, 0.26)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  landingBadge: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(10),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  landingBadgeText: {
    color: '#F5FFF9',
    fontSize: responsiveFontSize(13),
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  landingVisual: {
    height: verticalScale(276),
    marginTop: verticalScale(22),
    marginBottom: verticalScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  landingOrbitalRing: {
    position: 'absolute',
    width: '100%', maxWidth: 208,
    height: verticalScale(208),
    borderRadius: moderateScale(999),
    borderWidth: 1.5,
    borderColor: 'rgba(213,255,236,0.22)',
    alignItems: 'center',
  },
  landingOrbitalDot: {
    width: scale(16),
    height: verticalScale(16),
    borderRadius: moderateScale(999),
    marginTop: verticalScale(9),
    backgroundColor: '#D5FFEC',
    shadowColor: '#D5FFEC',
    shadowOpacity: 0.76,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  landingLogoCoreShell: {
    width: scale(156),
    height: verticalScale(156),
    borderRadius: moderateScale(999),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    shadowColor: '#9DF4CA',
    shadowOpacity: 0.2,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: verticalScale(14) },
    elevation: 10,
  },
  landingStatCard: {
    position: 'absolute',
    width: scale(126),
    borderRadius: moderateScale(24),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(14),
    backgroundColor: '#F4FFF9',
    shadowColor: '#042821',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 8,
  },
  landingStatLeft: {
    left: 0,
    top: verticalScale(38),
  },
  landingStatRight: {
    right: 0,
    bottom: verticalScale(28),
  },
  landingStatTitle: {
    marginTop: verticalScale(8),
    fontSize: responsiveFontSize(13),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  landingStatValue: {
    marginTop: verticalScale(4),
    fontSize: responsiveFontSize(13),
    lineHeight: moderateScale(18),
    color: ecoTheme.colors.textSoft,
  },
  landingTitle: {
    fontSize: responsiveFontSize(34),
    lineHeight: moderateScale(41),
    fontWeight: '900',
    color: '#F7FFF9',
    textAlign: 'center',
  },
  landingCopy: {
    marginTop: verticalScale(14),
    fontSize: responsiveFontSize(16),
    lineHeight: moderateScale(25),
    color: 'rgba(239,255,247,0.84)',
    textAlign: 'center',
  },
  landingFeatureList: {
    marginTop: verticalScale(22),
    gap: 12,
  },
  landingFeaturePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: moderateScale(22),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(14),
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  landingFeatureIcon: {
    width: scale(40),
    height: verticalScale(40),
    borderRadius: moderateScale(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  landingFeatureTextWrap: {
    flex: 1,
  },
  landingFeatureTitle: {
    fontSize: responsiveFontSize(15),
    fontWeight: '800',
    color: '#F7FFF9',
  },
  landingFeatureSubtitle: {
    marginTop: verticalScale(2),
    fontSize: responsiveFontSize(13),
    lineHeight: moderateScale(18),
    color: 'rgba(235,255,244,0.72)',
  },
  landingActions: {
    marginTop: verticalScale(24),
    gap: 12,
  },
  landingFootnote: {
    marginTop: verticalScale(16),
    fontSize: responsiveFontSize(13),
    fontWeight: '700',
    color: 'rgba(229,255,240,0.62)',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: '#0D4238',
  },
  onboardingBackdropImage: {
    ...StyleSheet.absoluteFill,
    opacity: 0.34,
  },
  onboardingBackdropTint: {
    ...StyleSheet.absoluteFill,
  },
  onboardingBackdropOrbTop: {
    position: 'absolute',
    top: verticalScale(-54),
    right: scale(-28),
    width: '100%', maxWidth: 232,
    height: verticalScale(232),
    borderRadius: moderateScale(116),
    backgroundColor: 'rgba(218,255,185,0.18)',
  },
  onboardingBackdropOrbBottom: {
    position: 'absolute',
    bottom: verticalScale(-88),
    left: scale(-62),
    width: '100%', maxWidth: 258,
    height: verticalScale(258),
    borderRadius: moderateScale(129),
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  onboardingBackdropLeafRight: {
    position: 'absolute',
    right: scale(-12),
    top: verticalScale(158),
    transform: [{ rotate: '8deg' }],
  },
  onboardingBackdropLeafLeft: {
    position: 'absolute',
    left: scale(-12),
    bottom: verticalScale(74),
    transform: [{ rotate: '-18deg' }],
  },
  onboardingBackdropLeafTop: {
    position: 'absolute',
    top: verticalScale(56),
    left: scale(18),
    transform: [{ rotate: '-12deg' }],
  },
  onboardingShell: {
    flex: 1,
    paddingHorizontal: scale(12),
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(12),
  },
  onboardingCard: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    borderRadius: moderateScale(36),
    paddingHorizontal: scale(22),
    paddingTop: verticalScale(24),
    paddingBottom: verticalScale(20),
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1.2,
    borderColor: 'rgba(255,255,255,0.32)',
    shadowColor: '#063D2E',
    shadowOpacity: 0.30,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: verticalScale(18) },
    elevation: 18,
    overflow: 'hidden',
  },
  onboardingCardCompact: {
    borderRadius: moderateScale(30),
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(14),
  },
  onboardingGlassLayer: {
    ...StyleSheet.absoluteFill,
    borderRadius: moderateScale(36),
  },
  onboardingCardTint: {
    ...StyleSheet.absoluteFill,
    borderRadius: moderateScale(36),
  },
  onboardingGlassShine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: verticalScale(180),
    borderTopLeftRadius: moderateScale(36),
    borderTopRightRadius: moderateScale(36),
  },
  onboardingGlassShimmer: {
    position: 'absolute',
    top: verticalScale(-40),
    left: scale(-40),
    width: '100%', maxWidth: 240,
    height: verticalScale(240),
    borderRadius: moderateScale(120),
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  onboardingFrostEdge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: moderateScale(36),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  onboardingCardGlow: {
    position: 'absolute',
    top: '30%',
    alignSelf: 'center',
    width: '100%', maxWidth: 280,
    height: verticalScale(280),
    borderRadius: moderateScale(140),
    backgroundColor: 'rgba(200,255,175,0.12)',
  },
  onboardingCardContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  onboardingBrandRow: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(4),
  },
  onboardingBrandImage: {
    width: scale(130),
    height: verticalScale(82),
  },
  onboardingBrandImageCompact: {
    width: scale(108),
    height: verticalScale(68),
  },
  onboardingHeroWrap: {
    marginTop: verticalScale(4),
    marginBottom: verticalScale(8),
  },
  onboardingHeroWrapCompact: {
    marginTop: 0,
    marginBottom: verticalScale(2),
  },
  onboardingStepContent: {
    flex: 1,
    width: '100%',
  },
  onboardingStepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: verticalScale(2),
  },
  onboardingStepEyebrowGlass: {
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderRadius: moderateScale(14),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(5),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  onboardingStepEyebrow: {
    fontSize: responsiveFontSize(11),
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: 'rgba(12, 71, 59, 0.78)',
  },
  onboardingStepCounter: {
    minHeight: 30,
    borderRadius: moderateScale(15),
    paddingHorizontal: scale(11),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  onboardingStepCounterText: {
    fontSize: responsiveFontSize(11),
    fontWeight: '800',
    letterSpacing: 0.8,
    color: '#134B3F',
  },
  onboardingShowcaseWrap: {
    width: '100%',
    minHeight: 286,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingShowcaseWrapCompact: {
    minHeight: 228,
  },
  onboardingHeroChip: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 42,
    borderRadius: moderateScale(22),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(10),
    shadowColor: '#0E5A4C',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 5,
  },
  onboardingHeroChipCompact: {
    minHeight: 38,
    borderRadius: moderateScale(20),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(8),
  },
  onboardingHeroChipLeft: {
    top: verticalScale(38),
    left: scale(4),
  },
  onboardingHeroChipRight: {
    top: verticalScale(84),
    right: scale(6),
  },
  onboardingHeroChipText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '800',
    color: '#145947',
  },
  onboardingHeroMetricChip: {
    position: 'absolute',
    bottom: verticalScale(22),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 176,
    borderRadius: moderateScale(28),
    paddingHorizontal: scale(18),
    paddingVertical: verticalScale(14),
    shadowColor: '#0B5F58',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 8,
  },
  onboardingHeroMetricChipCompact: {
    bottom: verticalScale(14),
    minWidth: 160,
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(11),
  },
  onboardingHeroMetricValue: {
    fontSize: responsiveFontSize(16),
    fontWeight: '900',
    color: '#F6FFF8',
  },
  onboardingHeroMetricLabel: {
    marginTop: verticalScale(4),
    fontSize: responsiveFontSize(12),
    fontWeight: '700',
    color: 'rgba(239,255,246,0.82)',
  },
  onboardingPreviewOrb: {
    position: 'absolute',
    width: '100%', maxWidth: 248,
    height: verticalScale(248),
    borderRadius: moderateScale(124),
    backgroundColor: 'rgba(220,255,194,0.24)',
  },
  onboardingPreviewPanel: {
    width: '100%',
    borderRadius: moderateScale(34),
    paddingHorizontal: scale(18),
    paddingTop: verticalScale(18),
    paddingBottom: verticalScale(16),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.62)',
    backgroundColor: 'rgba(255,255,255,0.26)',
  },
  onboardingPreviewPanelCompact: {
    borderRadius: moderateScale(28),
    paddingHorizontal: scale(14),
    paddingTop: verticalScale(14),
    paddingBottom: verticalScale(12),
  },
  onboardingPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(14),
    gap: 12,
  },
  onboardingPreviewStepLabel: {
    fontSize: responsiveFontSize(12),
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: 'rgba(18, 73, 60, 0.62)',
  },
  onboardingPreviewTitle: {
    marginTop: verticalScale(4),
    fontSize: responsiveFontSize(20),
    fontWeight: '900',
    color: '#143A31',
  },
  onboardingPreviewBadge: {
    width: scale(42),
    height: verticalScale(42),
    borderRadius: moderateScale(21),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  onboardingPreviewFeatureStack: {
    gap: 10,
  },
  onboardingPreviewFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: moderateScale(22),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(12),
    backgroundColor: 'rgba(255,255,255,0.60)',
  },
  onboardingPreviewFeatureRowCompact: {
    gap: 10,
    borderRadius: moderateScale(20),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(10),
  },
  onboardingPreviewFeatureIcon: {
    width: scale(42),
    height: verticalScale(42),
    borderRadius: moderateScale(21),
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingPreviewFeatureTextWrap: {
    flex: 1,
  },
  onboardingPreviewFeatureTitle: {
    fontSize: responsiveFontSize(15),
    fontWeight: '800',
    color: '#143A31',
  },
  onboardingPreviewFeatureDetail: {
    marginTop: verticalScale(3),
    fontSize: responsiveFontSize(13),
    lineHeight: moderateScale(18),
    color: 'rgba(20, 58, 49, 0.74)',
  },
  onboardingPreviewFooter: {
    marginTop: verticalScale(14),
    borderRadius: moderateScale(18),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(12),
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  onboardingPreviewFooterText: {
    flex: 1,
    fontSize: responsiveFontSize(13),
    lineHeight: moderateScale(18),
    fontWeight: '700',
    color: '#145947',
  },
  illustrationWrap: {
    width: '100%', maxWidth: 320,
    height: verticalScale(330),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  illustrationAura: {
    position: 'absolute',
    width: '100%', maxWidth: 272,
    height: verticalScale(272),
    borderRadius: moderateScale(136),
    backgroundColor: 'rgba(223,255,186,0.18)',
  },
  illustrationAuraSecondary: {
    position: 'absolute',
    width: '100%', maxWidth: 320,
    height: verticalScale(228),
    borderRadius: moderateScale(118),
    backgroundColor: 'rgba(244,255,239,0.20)',
    transform: [{ translateY: 18 }],
  },
  illustrationBubble: {
    position: 'absolute',
    bottom: verticalScale(38),
    width: '100%', maxWidth: 286,
    height: verticalScale(224),
    borderRadius: moderateScale(118),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.46)',
  },
  illustrationGlowDotOne: {
    position: 'absolute',
    left: scale(54),
    top: verticalScale(126),
    width: scale(12),
    height: verticalScale(12),
    borderRadius: moderateScale(6),
    backgroundColor: '#F7FFD4',
    shadowColor: '#F7FFD4',
    shadowOpacity: 0.7,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationGlowDotTwo: {
    position: 'absolute',
    right: scale(56),
    top: verticalScale(152),
    width: scale(10),
    height: verticalScale(10),
    borderRadius: moderateScale(5),
    backgroundColor: '#FFF3C8',
    shadowColor: '#FFF3C8',
    shadowOpacity: 0.74,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationGlowDotThree: {
    position: 'absolute',
    right: scale(88),
    bottom: verticalScale(76),
    width: scale(8),
    height: verticalScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: '#FBFFE5',
    shadowColor: '#FBFFE5',
    shadowOpacity: 0.74,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationDewDrop: {
    position: 'absolute',
    backgroundColor: 'rgba(255,255,255,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.46)',
  },
  illustrationDewDropOne: {
    top: verticalScale(78),
    left: scale(56),
    width: scale(22),
    height: verticalScale(30),
    borderRadius: moderateScale(14),
  },
  illustrationDewDropTwo: {
    top: verticalScale(96),
    right: scale(46),
    width: scale(16),
    height: verticalScale(24),
    borderRadius: moderateScale(12),
  },
  illustrationDewDropThree: {
    right: scale(74),
    bottom: verticalScale(118),
    width: scale(18),
    height: verticalScale(26),
    borderRadius: moderateScale(13),
  },
  illustrationLeafBadge: {
    position: 'absolute',
    width: scale(54),
    height: verticalScale(76),
    borderRadius: moderateScale(28),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D9FFCE',
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 6,
  },
  illustrationLeafBadgeOne: {
    left: scale(44),
    top: verticalScale(34),
  },
  illustrationLeafBadgeTwo: {
    left: scale(86),
    top: verticalScale(10),
  },
  illustrationLeafBadgeThree: {
    left: scale(134),
    top: 0,
  },
  illustrationLeafBadgeFour: {
    right: scale(86),
    top: verticalScale(14),
  },
  illustrationLeafBadgeFive: {
    right: scale(46),
    top: verticalScale(46),
  },
  illustrationLeafVein: {
    width: scale(4),
    height: verticalScale(44),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(255,255,255,0.62)',
  },
  illustrationStemLeft: {
    position: 'absolute',
    left: scale(68),
    bottom: verticalScale(64),
    width: scale(4),
    height: verticalScale(78),
    borderRadius: moderateScale(999),
    backgroundColor: '#6FA863',
    transform: [{ rotate: '-12deg' }],
  },
  illustrationStemCenter: {
    position: 'absolute',
    left: scale(116),
    bottom: verticalScale(58),
    width: scale(5),
    height: verticalScale(94),
    borderRadius: moderateScale(999),
    backgroundColor: '#73B468',
  },
  illustrationStemRight: {
    position: 'absolute',
    right: scale(72),
    bottom: verticalScale(58),
    width: scale(4),
    height: verticalScale(82),
    borderRadius: moderateScale(999),
    backgroundColor: '#6FA863',
    transform: [{ rotate: '12deg' }],
  },
  illustrationSproutLeaf: {
    position: 'absolute',
    width: scale(26),
    height: verticalScale(14),
    borderRadius: moderateScale(999),
    backgroundColor: '#82C776',
  },
  illustrationSproutLeafLeft: {
    left: scale(52),
    bottom: verticalScale(128),
    transform: [{ rotate: '-26deg' }],
  },
  illustrationSproutLeafRight: {
    right: scale(56),
    bottom: verticalScale(116),
    transform: [{ rotate: '26deg' }],
  },
  illustrationFlower: {
    position: 'absolute',
    width: scale(44),
    height: verticalScale(44),
    alignItems: 'center',
    justifyContent: 'center',
  },
  illustrationFlowerLeft: {
    left: scale(30),
    bottom: verticalScale(34),
  },
  illustrationFlowerCenter: {
    left: scale(126),
    bottom: verticalScale(48),
  },
  illustrationFlowerRight: {
    right: scale(34),
    bottom: verticalScale(32),
  },
  illustrationFlowerPetal: {
    position: 'absolute',
    width: scale(18),
    height: verticalScale(18),
    borderRadius: moderateScale(999),
  },
  illustrationFlowerPetalTop: {
    top: 0,
  },
  illustrationFlowerPetalRight: {
    right: 0,
  },
  illustrationFlowerPetalBottom: {
    bottom: 0,
  },
  illustrationFlowerPetalLeft: {
    left: 0,
  },
  illustrationFlowerCore: {
    width: scale(16),
    height: verticalScale(16),
    borderRadius: moderateScale(999),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.36)',
  },
  illustrationLeafPodLeft: {
    position: 'absolute',
    left: scale(18),
    bottom: verticalScale(74),
    width: scale(76),
    height: verticalScale(34),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(130, 198, 116, 0.42)',
    justifyContent: 'center',
    transform: [{ rotate: '-16deg' }],
  },
  illustrationLeafPodRight: {
    position: 'absolute',
    right: scale(18),
    bottom: verticalScale(84),
    width: scale(76),
    height: verticalScale(34),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(130, 198, 116, 0.38)',
    justifyContent: 'center',
    transform: [{ rotate: '18deg' }],
  },
  illustrationLeafPodInner: {
    width: scale(42),
    height: verticalScale(18),
    borderRadius: moderateScale(999),
    marginHorizontal: scale(14),
    backgroundColor: 'rgba(240,255,237,0.58)',
  },
  illustrationCharacter: {
    position: 'absolute',
    bottom: verticalScale(62),
    width: scale(164),
    height: verticalScale(198),
    borderRadius: moderateScale(80),
    alignItems: 'center',
    paddingTop: verticalScale(86),
    shadowColor: '#D7FFC3',
    shadowOpacity: 0.42,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: verticalScale(16) },
    elevation: 12,
  },
  illustrationCharacterGlow: {
    position: 'absolute',
    top: verticalScale(10),
    left: scale(12),
    right: scale(12),
    bottom: verticalScale(20),
    borderRadius: moderateScale(64),
    backgroundColor: 'rgba(255,255,255,0.20)',
  },
  illustrationArm: {
    position: 'absolute',
    top: verticalScale(92),
    width: scale(54),
    height: verticalScale(58),
    borderRadius: moderateScale(28),
    backgroundColor: '#B7EA8A',
  },
  illustrationArmLeft: {
    left: scale(-18),
    transform: [{ rotate: '20deg' }],
  },
  illustrationArmRight: {
    right: scale(-18),
    transform: [{ rotate: '-18deg' }],
  },
  illustrationLeg: {
    position: 'absolute',
    bottom: verticalScale(-22),
    width: scale(44),
    height: verticalScale(56),
    borderRadius: moderateScale(24),
    backgroundColor: '#8ACA6C',
  },
  illustrationLegLeft: {
    left: scale(34),
  },
  illustrationLegRight: {
    right: scale(34),
  },
  illustrationEyeRow: {
    flexDirection: 'row',
    gap: 26,
  },
  illustrationEye: {
    width: scale(18),
    height: verticalScale(24),
    borderRadius: moderateScale(12),
    backgroundColor: '#224C37',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: verticalScale(4),
  },
  illustrationEyeSpark: {
    width: scale(6),
    height: verticalScale(6),
    borderRadius: moderateScale(999),
    backgroundColor: '#FFFFFF',
  },
  illustrationSmile: {
    width: scale(34),
    height: verticalScale(16),
    marginTop: verticalScale(12),
    borderBottomWidth: 4,
    borderColor: '#2C6E46',
    borderRadius: moderateScale(999),
  },
  illustrationBlush: {
    position: 'absolute',
    top: verticalScale(116),
    width: scale(24),
    height: verticalScale(12),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(255, 174, 146, 0.56)',
  },
  illustrationBlushLeft: {
    left: scale(30),
  },
  illustrationBlushRight: {
    right: scale(30),
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: verticalScale(20),
  },
  logoRowHero: {
    marginBottom: 0,
    gap: 14,
  },
  logoBadge: {
    width: scale(42),
    height: verticalScale(42),
    borderRadius: moderateScale(21),
    backgroundColor: '#DDF5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoBadgeLight: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  logoBadgeHero: {
    width: scale(56),
    height: verticalScale(56),
    borderRadius: moderateScale(28),
  },
  logoText: {
    fontSize: responsiveFontSize(22),
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
    letterSpacing: 0.4,
  },
  logoTextHero: {
    fontSize: responsiveFontSize(28),
    letterSpacing: 1.2,
  },
  logoTextLight: {
    color: '#FFFFFF',
  },
  onboardingTitle: {
    fontSize: responsiveFontSize(28),
    lineHeight: moderateScale(36),
    fontWeight: '700',
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: undefined }),
    textAlign: 'center',
    color: '#151A16',
    marginBottom: verticalScale(6),
  },
  onboardingTitleCompact: {
    fontSize: responsiveFontSize(22),
    lineHeight: moderateScale(28),
    marginBottom: verticalScale(4),
  },
  onboardingCopy: {
    fontSize: responsiveFontSize(14),
    lineHeight: moderateScale(21),
    color: '#21342B',
    textAlign: 'center',
    marginBottom: verticalScale(8),
  },
  onboardingCopyCompact: {
    fontSize: responsiveFontSize(12),
    lineHeight: moderateScale(17),
    marginBottom: verticalScale(6),
  },
  onboardingSpotlightGlass: {
    marginBottom: verticalScale(10),
    borderRadius: moderateScale(18),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.30)',
  },
  onboardingSpotlightGlassCompact: {
    marginBottom: verticalScale(6),
    borderRadius: moderateScale(14),
  },
  onboardingSpotlightInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(10),
  },
  onboardingSpotlightText: {
    flex: 1,
    fontSize: responsiveFontSize(13),
    lineHeight: moderateScale(18),
    fontWeight: '700',
    color: '#145947',
  },
  onboardingBottomActions: {
    gap: 6,
  },
  onboardingExistingAccount: {
    marginTop: verticalScale(4),
    alignSelf: 'center',
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
  },
  onboardingExistingAccountText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '700',
    color: 'rgba(21, 26, 22, 0.50)',
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: moderateScale(30),
    overflow: 'hidden',
    shadowColor: '#13917B',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonGradient: {
    minHeight: 58,
    borderRadius: moderateScale(30),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(22),
    overflow: 'hidden',
  },
  primaryButtonGlow: {
    position: 'absolute',
    width: scale(132),
    height: verticalScale(132),
    top: verticalScale(-82),
    right: scale(-18),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  primaryButtonText: {
    fontSize: responsiveFontSize(18),
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: moderateScale(24),
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    overflow: 'hidden',
  },
  secondaryButtonGradient: {
    minHeight: 50,
    borderRadius: moderateScale(24),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(20),
  },
  secondaryButtonText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  paginationDots: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: verticalScale(6),
    gap: 8,
  },
  dot: {
    width: scale(8),
    height: verticalScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: 'rgba(76, 117, 76, 0.22)',
  },
  dotActive: {
    width: scale(28),
    backgroundColor: '#72B865',
  },
  newOnboardingContainer: {
    flex: 1,
    backgroundColor: '#EBF5ED',
  },
  newOnboardingSafeArea: {
    flex: 1,
    justifyContent: 'space-between',
  },
  newOnboardingHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: verticalScale(36),
    marginBottom: verticalScale(12),
    paddingHorizontal: scale(24),
  },
  newOnboardingLogo: {
    width: scale(150),
    height: scale(150) * (238 / 691),
    resizeMode: 'contain',
  },
  newOnboardingHeroContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    marginTop: verticalScale(-10),
  },
  heroCircleWrapper: {
    width: '80%',
    maxWidth: scale(280),
    aspectRatio: 1,
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#13917B',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 8,
  },
  newOnboardingHeroImage: {
    width: '125%',
    height: '125%',
  },
  newOnboardingTextContainer: {
    paddingHorizontal: scale(24),
    alignItems: 'center',
    marginBottom: verticalScale(24),
    flexShrink: 1,
  },
  newOnboardingTitle: {
    fontWeight: '800',
    fontSize: responsiveFontSize(30),
    color: '#123D2B',
    textAlign: 'center',
    marginBottom: verticalScale(12),
    lineHeight: moderateScale(36),
    flexShrink: 1,
  },
  newOnboardingSubtitle: {
    fontSize: responsiveFontSize(15),
    fontWeight: '500',
    color: '#123D2B',
    textAlign: 'center',
    lineHeight: moderateScale(22),
    paddingHorizontal: scale(8),
    flexShrink: 1,
    opacity: 0.85,
  },
  newOnboardingBottom: {
    paddingHorizontal: scale(24),
    paddingBottom: Platform.OS === 'ios' ? verticalScale(10) : verticalScale(28),
  },
  newOnboardingButton: {
    backgroundColor: '#519E59',
    borderRadius: moderateScale(30),
    minHeight: verticalScale(56),
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(8),
    marginBottom: verticalScale(24),
  },
  newOnboardingButtonText: {
    fontWeight: '700',
    color: '#FFFFFF',
    fontSize: responsiveFontSize(18),
  },
  newOnboardingPagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: verticalScale(24),
    marginBottom: Platform.OS === 'ios' ? 10 : 0,
  },
  newOnboardingDot: {
    width: scale(8),
    height: verticalScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: '#C8D7CD',
  },
  newOnboardingDotActive: {
    width: scale(24),
    backgroundColor: '#519E59',
  },
  authShell: {
    flexGrow: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  authHero: {
    paddingHorizontal: scale(24),
    paddingVertical: verticalScale(32),
    borderBottomLeftRadius: moderateScale(36),
    borderBottomRightRadius: moderateScale(36),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  authTitle: {
    fontSize: responsiveFontSize(34),
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: verticalScale(12),
  },
  authSubtitle: {
    marginTop: verticalScale(12),
    fontSize: responsiveFontSize(16),
    lineHeight: moderateScale(24),
    color: 'rgba(255,255,255,0.88)',
  },
  authCard: {
    marginHorizontal: scale(18),
    marginTop: verticalScale(-26),
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: ecoTheme.radius.xl,
    padding: moderateScale(22),
    borderWidth: 1,
    borderColor: '#E2EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 6,
  },
  sectionHeadline: {
    fontSize: responsiveFontSize(22),
    fontWeight: '900',
    color: ecoTheme.colors.text,
    marginBottom: verticalScale(10),
  },
  sectionCaption: {
    fontSize: responsiveFontSize(15),
    lineHeight: moderateScale(22),
    color: ecoTheme.colors.textSoft,
  },
  quickLoginRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: verticalScale(18),
    marginBottom: verticalScale(10),
  },
  quickPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    borderRadius: moderateScale(24),
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    backgroundColor: '#F6FBF8',
    overflow: 'hidden',
  },
  quickPillActive: {
    borderColor: ecoTheme.colors.primaryDark,
    shadowColor: '#158771',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 4,
  },
  quickPillGradient: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
  },
  quickPillText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  quickPillTextActive: {
    color: '#FFFFFF',
  },
  inputGroup: {
    marginTop: verticalScale(16),
  },
  inputLabel: {
    marginBottom: verticalScale(8),
    fontSize: responsiveFontSize(14),
    fontWeight: '700',
    color: ecoTheme.colors.text,
  },
  textInput: {
    minHeight: 54,
    borderRadius: moderateScale(18),
    backgroundColor: '#F7FBF8',
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    paddingHorizontal: scale(16),
    fontSize: responsiveFontSize(16),
    color: ecoTheme.colors.text,
  },
  authError: {
    color: '#C44536',
    fontSize: responsiveFontSize(14),
    marginTop: verticalScale(12),
    marginBottom: verticalScale(6),
  },
  authHintBox: {
    marginTop: verticalScale(18),
    backgroundColor: '#F5FBF7',
    borderRadius: moderateScale(18),
    padding: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E0EFE3',
  },
  authHintTitle: {
    fontSize: responsiveFontSize(14),
    fontWeight: '800',
    color: ecoTheme.colors.text,
    marginBottom: verticalScale(6),
  },
  authHintCopy: {
    fontSize: responsiveFontSize(13),
    color: ecoTheme.colors.textSoft,
    lineHeight: moderateScale(20),
  },
  mainScrollContent: {
    paddingBottom: verticalScale(110),
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  homeHero: {
    paddingHorizontal: scale(22),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(34),
    borderBottomLeftRadius: moderateScale(36),
    borderBottomRightRadius: moderateScale(36),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    shadowColor: '#0C5A4D',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: verticalScale(10) },
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  homeHeroGreeting: {
    fontSize: responsiveFontSize(42),
    lineHeight: moderateScale(48),
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: verticalScale(26),
  },
  homeHeroSubcopy: {
    marginTop: verticalScale(10),
    fontSize: responsiveFontSize(18),
    color: 'rgba(255,255,255,0.90)',
  },
  notificationBubble: {
    width: scale(42),
    height: verticalScale(42),
    borderRadius: moderateScale(21),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    right: scale(-3),
    top: verticalScale(-4),
    minWidth: 22,
    height: verticalScale(22),
    borderRadius: moderateScale(11),
    backgroundColor: '#E15A4E',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(5),
  },
  notificationBadgeText: {
    fontSize: responsiveFontSize(11),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  contentSection: {
    paddingHorizontal: scale(18),
    paddingTop: verticalScale(18),
    gap: 18,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metricTile: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: moderateScale(20),
    paddingVertical: verticalScale(16),
    paddingHorizontal: scale(10),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E3EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 4,
  },
  metricValue: {
    marginTop: verticalScale(8),
    fontSize: responsiveFontSize(18),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  metricLabel: {
    marginTop: verticalScale(6),
    fontSize: responsiveFontSize(14),
    color: ecoTheme.colors.textSoft,
  },
  surfaceCard: {
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: ecoTheme.radius.lg,
    padding: moderateScale(18),
    borderWidth: 1,
    borderColor: '#E4F0E8',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: verticalScale(10) },
    elevation: 4,
  },
  challengeFeatureCard: {
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  iconBadge: {
    width: scale(34),
    height: verticalScale(34),
    borderRadius: moderateScale(17),
    backgroundColor: '#E7F6EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  linkText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  challengeHeadline: {
    fontSize: responsiveFontSize(18),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  rowMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: responsiveFontSize(14),
    color: ecoTheme.colors.textSoft,
  },
  progressLabel: {
    fontSize: responsiveFontSize(15),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  progressTrack: {
    height: verticalScale(12),
    borderRadius: moderateScale(8),
    backgroundColor: '#E4E9E6',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: moderateScale(8),
    backgroundColor: '#249D7A',
  },
  horizontalList: {
    gap: 14,
    paddingRight: scale(8),
  },
  lessonHighlightCard: {
    width: '100%', maxWidth: 250,
    backgroundColor: '#FFFFFF',
    borderRadius: ecoTheme.radius.lg,
    overflow: 'hidden',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 3,
  },
  lessonHighlightBody: {
    padding: moderateScale(16),
    gap: 8,
  },
  lessonHighlightTitle: {
    fontSize: responsiveFontSize(18),
    lineHeight: moderateScale(24),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  lessonMedia: {
    width: '100%',
    borderRadius: moderateScale(20),
    backgroundColor: '#C7E9CD',
  },
  lessonMediaFallback: {
    width: '100%',
    borderRadius: moderateScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  actionCard: {
    width: '48%',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: moderateScale(22),
    padding: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E3EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 3,
  },
  actionIconBubble: {
    width: scale(42),
    height: verticalScale(42),
    borderRadius: moderateScale(21),
    backgroundColor: '#E8F6EE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(10),
  },
  actionCardTitle: {
    fontSize: responsiveFontSize(17),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  actionCardSubtitle: {
    marginTop: verticalScale(6),
    fontSize: responsiveFontSize(14),
    color: ecoTheme.colors.textSoft,
  },
  pageHeader: {
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(14),
    paddingBottom: verticalScale(28),
    borderBottomLeftRadius: moderateScale(34),
    borderBottomRightRadius: moderateScale(34),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  pageHeaderTitle: {
    fontSize: responsiveFontSize(28),
    fontWeight: '900',
    color: '#FFFFFF',
  },
  pageHeaderSubtitle: {
    marginTop: verticalScale(8),
    fontSize: responsiveFontSize(16),
    color: 'rgba(255,255,255,0.88)',
  },
  searchField: {
    minHeight: 54,
    borderRadius: moderateScale(18),
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: '#E3E9E4',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: scale(16),
  },
  searchInput: {
    flex: 1,
    fontSize: responsiveFontSize(16),
    color: ecoTheme.colors.text,
  },
  featuredLessonCard: {
    gap: 14,
  },
  featuredOverlay: {
    position: 'absolute',
    left: '50%',
    top: verticalScale(92),
    marginLeft: scale(-30),
    width: scale(60),
    height: verticalScale(60),
    borderRadius: moderateScale(30),
    backgroundColor: 'rgba(47, 165, 95, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  courseRowCard: {
    gap: 10,
  },
  courseRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  courseRowTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  coursePercent: {
    alignSelf: 'flex-end',
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.textSoft,
  },
  habitsCard: {
    gap: 12,
    backgroundColor: '#EEF7F1',
  },
  habitRow: {
    minHeight: 58,
    borderRadius: moderateScale(18),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: scale(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  habitTitle: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.text,
    flex: 1,
    flexShrink: 1,
    marginRight: scale(8),
  },
  pointsPill: {
    minWidth: 60,
    minHeight: 34,
    borderRadius: moderateScale(17),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5F7EE',
    paddingHorizontal: scale(10),
  },
  pointsPillMuted: {
    backgroundColor: '#E4F7E9',
  },
  pointsPillText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '800',
    color: ecoTheme.colors.primaryDark,
  },
  pointsEarnedText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
    textAlign: 'center',
  },
  challengeListCard: {
    padding: moderateScale(14),
  },
  challengeListTop: {
    flexDirection: 'row',
    gap: 14,
  },
  miniMedia: {
    width: scale(100),
    height: verticalScale(100),
    borderRadius: moderateScale(18),
    backgroundColor: '#C9ECD0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  challengeContent: {
    flex: 1,
    gap: 8,
  },
  challengeListTitle: {
    flex: 1,
    fontSize: responsiveFontSize(18),
    lineHeight: moderateScale(24),
    fontWeight: '900',
    color: ecoTheme.colors.text,
    marginRight: scale(10),
  },
  challengeMetaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  challengeActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: verticalScale(6),
  },
  inlinePanelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 52,
    borderRadius: moderateScale(22),
    backgroundColor: '#EAF8EF',
    borderWidth: 1,
    borderColor: '#DCEEDF',
  },
  inlinePanelButtonText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  trackerHeroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trackerHeroLeft: {
    flex: 1,
    paddingRight: scale(14),
  },
  trackerHeroTitle: {
    fontSize: responsiveFontSize(20),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  trackerHeroStreak: {
    fontSize: responsiveFontSize(24),
    lineHeight: moderateScale(32),
    fontWeight: '900',
    color: '#111111',
    marginVertical: verticalScale(8),
  },
  progressRingOuter: {
    width: scale(120),
    height: verticalScale(120),
    borderRadius: moderateScale(60),
    borderWidth: 14,
    borderColor: '#D9F0DE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressRingInner: {
    width: scale(78),
    height: verticalScale(78),
    borderRadius: moderateScale(39),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  progressRingValue: {
    fontSize: responsiveFontSize(28),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  calendarCard: {
    gap: 16,
  },
  calendarMonth: {
    fontSize: responsiveFontSize(18),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarWeekLabel: {
    width: '14.2%',
    textAlign: 'center',
    fontSize: responsiveFontSize(14),
    color: ecoTheme.colors.textSoft,
    fontWeight: '700',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    width: '14.2%',
    alignItems: 'center',
    marginBottom: verticalScale(10),
  },
  calendarBubble: {
    width: scale(38),
    height: verticalScale(38),
    borderRadius: moderateScale(19),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F7F4',
  },
  calendarBubbleActive: {
    backgroundColor: '#55B85D',
  },
  calendarBubbleToday: {
    borderWidth: 2,
    borderColor: ecoTheme.colors.primaryDark,
  },
  calendarBubbleText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.text,
  },
  calendarBubbleTextActive: {
    color: '#FFFFFF',
  },
  calendarBubblePlaceholder: {
    width: scale(38),
    height: verticalScale(38),
  },
  checkInCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkInTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  checkInButton: {
    minWidth: 110,
  },
  profileSummaryCard: {
    gap: 16,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatarBubble: {
    backgroundColor: '#CBEFD6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontSize: responsiveFontSize(22),
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  profileName: {
    fontSize: responsiveFontSize(22),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  profilePointsPill: {
    borderRadius: moderateScale(20),
    backgroundColor: '#ECFAEF',
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(10),
  },
  profilePointsText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  profileMetric: {
    flex: 1,
    borderRadius: moderateScale(18),
    backgroundColor: '#F5FBF7',
    padding: moderateScale(14),
    alignItems: 'center',
  },
  profileMetricValue: {
    fontSize: responsiveFontSize(20),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  profileMetricLabel: {
    marginTop: verticalScale(6),
    fontSize: responsiveFontSize(13),
    color: ecoTheme.colors.textSoft,
  },
  badgeCard: {
    flex: 1,
    maxWidth: 180,
    minHeight: 180,
    borderRadius: moderateScale(20),
    borderWidth: 1.5,
    borderColor: '#31B65B',
    backgroundColor: '#FFFFFF',
    padding: moderateScale(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeCardFull: {
    width: '48%',
  },
  badgeCardLocked: {
    borderColor: '#B8B8B8',
    backgroundColor: '#E4E4E4',
  },
  badgeIconWrap: {
    width: scale(62),
    height: verticalScale(62),
    borderRadius: moderateScale(31),
    backgroundColor: '#EDF9F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(14),
  },
  badgeIconWrapLocked: {
    backgroundColor: '#D2D2D2',
  },
  badgeName: {
    fontSize: responsiveFontSize(20),
    lineHeight: moderateScale(24),
    textAlign: 'center',
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  badgeRequirement: {
    fontSize: responsiveFontSize(14),
    lineHeight: moderateScale(20),
    textAlign: 'center',
    color: ecoTheme.colors.textSoft,
    marginTop: verticalScale(10),
  },
  logPreviewCard: {
    gap: 10,
  },
  logPoints: {
    fontSize: responsiveFontSize(15),
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  hashText: {
    fontSize: responsiveFontSize(14),
    color: '#8A94A0',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  overlayShell: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  overlayHeader: {
    paddingHorizontal: scale(20),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(28),
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backLabel: {
    fontSize: responsiveFontSize(16),
    color: '#FFFFFF',
    fontWeight: '700',
  },
  overlayTitle: {
    fontSize: responsiveFontSize(34),
    lineHeight: moderateScale(40),
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: verticalScale(18),
  },
  overlaySubtitle: {
    marginTop: verticalScale(8),
    fontSize: responsiveFontSize(16),
    color: 'rgba(255,255,255,0.88)',
  },
  overlayBody: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
    borderTopLeftRadius: moderateScale(28),
    borderTopRightRadius: moderateScale(28),
    marginTop: verticalScale(-12),
    overflow: 'hidden',
  },
  overlayScroll: {
    padding: moderateScale(18),
    gap: 16,
  },
  assistantHero: {
    alignItems: 'center',
    paddingTop: verticalScale(18),
  },
  assistantMascot: {
    width: scale(92),
    height: verticalScale(92),
    borderRadius: moderateScale(46),
    backgroundColor: '#ECF8EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  assistantThread: {
    paddingHorizontal: scale(18),
    paddingVertical: verticalScale(16),
    gap: 12,
  },
  assistantBubble: {
    maxWidth: '85%',
    borderRadius: moderateScale(22),
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(14),
  },
  assistantBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#FFFFFF',
  },
  assistantBubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: '#DFF6E4',
  },
  assistantBubbleText: {
    fontSize: responsiveFontSize(18),
    lineHeight: moderateScale(26),
    color: ecoTheme.colors.text,
  },
  assistantTime: {
    marginTop: verticalScale(8),
    fontSize: responsiveFontSize(12),
    color: ecoTheme.colors.textSoft,
  },
  quickReplyWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: scale(18),
    paddingBottom: verticalScale(14),
  },
  quickReplyChip: {
    minHeight: 42,
    borderRadius: moderateScale(22),
    borderWidth: 1,
    borderColor: ecoTheme.colors.primary,
    paddingHorizontal: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0FBF3',
  },
  quickReplyText: {
    fontSize: responsiveFontSize(15),
    color: ecoTheme.colors.primaryDark,
    fontWeight: '700',
  },
  assistantComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: scale(18),
    paddingBottom: verticalScale(22),
  },
  assistantInput: {
    flex: 1,
    minHeight: 54,
    borderRadius: moderateScale(27),
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: scale(18),
    fontSize: responsiveFontSize(16),
    color: ecoTheme.colors.text,
  },
  sendButton: {
    width: scale(54),
    height: verticalScale(54),
    borderRadius: moderateScale(27),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ecoTheme.colors.primaryDark,
  },
  segmentedControl: {
    flexDirection: 'row',
    margin: moderateScale(18),
    marginBottom: 0,
    backgroundColor: '#E8ECE8',
    borderRadius: moderateScale(24),
    padding: moderateScale(4),
  },
  segmentActive: {
    flex: 1,
    minHeight: 46,
    borderRadius: moderateScale(22),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentInactive: {
    flex: 1,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActiveText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  segmentInactiveText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: ecoTheme.colors.textSoft,
  },
  eventCard: {
    gap: 12,
  },
  eventJoinButton: {
    minWidth: 110,
    flex: 0,
  },
  lessonDetailCard: {
    gap: 14,
  },
  lessonMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  lessonBodyText: {
    fontSize: responsiveFontSize(16),
    lineHeight: moderateScale(26),
    color: ecoTheme.colors.text,
  },
  leaderboardCard: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  leaderboardCardActive: {
    backgroundColor: '#E8F6EE',
  },
  rankLabel: {
    width: scale(58),
    fontSize: responsiveFontSize(18),
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  leaderboardName: {
    fontSize: responsiveFontSize(18),
    fontWeight: '900',
    color: ecoTheme.colors.text,
    flex: 1,
    flexShrink: 1,
  },
  badgePillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: verticalScale(8),
  },
  tinyBadge: {
    minHeight: 30,
    borderRadius: moderateScale(16),
    backgroundColor: '#EEF8F1',
    paddingHorizontal: scale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  tinyBadgeGold: {
    backgroundColor: '#F6E4A3',
  },
  tinyBadgeText: {
    fontSize: responsiveFontSize(13),
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  tinyBadgeTextGold: {
    color: '#856400',
  },
  rewardsHeroCard: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardsHeroValue: {
    fontSize: responsiveFontSize(34),
    lineHeight: moderateScale(40),
    fontWeight: '900',
    color: ecoTheme.colors.primary,
  },
  badgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  achievementCard: {
    gap: 12,
  },
  timelineRail: {
    gap: 10,
  },
  timelineRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  timelineNodeWrap: {
    width: scale(26),
    alignItems: 'center',
  },
  timelineNode: {
    width: scale(18),
    height: verticalScale(18),
    borderRadius: moderateScale(9),
    backgroundColor: ecoTheme.colors.primaryDark,
    borderWidth: 4,
    borderColor: '#D4EFE1',
    marginTop: verticalScale(16),
  },
  timelineLine: {
    width: scale(4),
    flex: 1,
    backgroundColor: '#CFEBDD',
    minHeight: 86,
    borderRadius: moderateScale(2),
  },
  timelineCard: {
    flex: 1,
    gap: 8,
    borderWidth: 1,
    borderColor: '#C3DFF5',
  },
  transparencyDetailCard: {
    gap: 10,
    borderWidth: 1,
    borderColor: '#D6EADF',
  },
  transparencyLine: {
    fontSize: responsiveFontSize(15),
    color: ecoTheme.colors.text,
  },
  bottomBar: {
    height: 64,
    borderRadius: moderateScale(24),
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderWidth: 1,
    borderColor: '#E2EBE5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#071C19',
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
    elevation: 8,
  },
  tabActivePill: {
    position: 'absolute',
    backgroundColor: '#EDF6F1',
    borderWidth: 1,
    borderColor: 'rgba(18, 96, 39, 0.14)',
    zIndex: 1,
  },
  bottomBarItem: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  bottomBarLabel: {
    fontSize: responsiveFontSize(11),
    fontWeight: '600',
    color: '#8A959F',
  },
  bottomBarLabelActive: {
    color: ecoTheme.colors.primaryDark,
    fontWeight: '800',
  },
  chatbotFabOuter: {
    position: 'absolute',
    right: scale(20),
    bottom: verticalScale(110),
    zIndex: 999,
  },
  chatbotFab: {
    shadowColor: '#10816A',
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: verticalScale(8) },
    elevation: 8,
    borderRadius: moderateScale(34),
  },
  chatbotFabImg: {
    width: scale(68),
    height: verticalScale(68),
    resizeMode: 'contain',
  },
  topNavbar: {
    paddingTop: verticalScale(50),
    paddingHorizontal: scale(24),
    paddingBottom: verticalScale(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7F9F7',
  },
  topNavAvatar: {
    borderWidth: 2,
    borderColor: '#4ADE80',
  },
  topNavAvatarText: {
    fontSize: responsiveFontSize(18),
  },
  topNavTitle: {
    fontSize: responsiveFontSize(22),
    fontWeight: '900',
    color: '#126027',
    letterSpacing: 2,
    flex: 1,
    textAlign: 'center',
  },
  topNavTitleDark: {
    color: '#1A211D',
  },
  topNavBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: scale(10),
    height: verticalScale(10),
    borderRadius: moderateScale(5),
    backgroundColor: '#F59E0B',
  },
  homeContent: {
    paddingHorizontal: scale(24),
    paddingBottom: verticalScale(24),
  },
  welcomeLabel: {
    fontSize: responsiveFontSize(12),
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1.5,
  },
  welcomeTitle: {
    fontSize: responsiveFontSize(32),
    fontWeight: '800',
    color: '#1A211D',
    marginTop: verticalScale(4),
  },
  welcomeSubtitle: {
    fontSize: responsiveFontSize(16),
    color: '#6B7A75',
    marginTop: verticalScale(4),
    marginBottom: verticalScale(24),
  },
  homeMetricRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: verticalScale(24),
  },
  homeMetricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    padding: moderateScale(20),
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
    elevation: 2,
  },
  homeMetricIconWrapBadge: {
    width: scale(36),
    height: verticalScale(36),
    borderRadius: moderateScale(18),
    backgroundColor: '#FDE68A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(16),
  },
  homeMetricValue: {
    fontSize: responsiveFontSize(32),
    fontWeight: '800',
    color: '#1A211D',
    marginBottom: verticalScale(4),
  },
  homeMetricLabel: {
    fontSize: responsiveFontSize(12),
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1,
  },
  weeklyGoalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    padding: moderateScale(20),
    marginBottom: verticalScale(24),
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
    elevation: 2,
  },
  weeklyGoalLabel: {
    fontSize: responsiveFontSize(12),
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1,
    marginBottom: verticalScale(12),
  },
  weeklyGoalTitle: {
    fontSize: responsiveFontSize(20),
    fontWeight: '700',
    color: '#1A211D',
    marginBottom: verticalScale(12),
  },
  weeklyGoalText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '600',
    color: '#6B7A75',
  },
  publicInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    padding: moderateScale(20),
    marginTop: verticalScale(16),
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
    elevation: 2,
  },
  todayChallengeCard: {
    backgroundColor: '#D4F7D4',
    borderRadius: moderateScale(24),
    padding: moderateScale(20),
    marginBottom: verticalScale(24),
    borderWidth: 1,
    borderColor: '#4ADE80',
  },
  challengeBadge: {
    backgroundColor: '#126027',
    alignSelf: 'flex-start',
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(12),
    marginBottom: verticalScale(16),
  },
  challengeBadgeText: {
    fontSize: responsiveFontSize(10),
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  todayChallengeTitle: {
    fontSize: responsiveFontSize(22),
    fontWeight: '700',
    color: '#126027',
    marginBottom: verticalScale(8),
  },
  todayChallengeDesc: {
    fontSize: responsiveFontSize(15),
    color: '#126027',
    opacity: 0.8,
    marginBottom: verticalScale(24),
  },
  challengeCompleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: verticalScale(14),
    borderRadius: moderateScale(16),
    gap: 8,
  },
  challengeCompleteBtnText: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: '#126027',
  },
  dailyTipCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    padding: moderateScale(16),
    alignItems: 'center',
    marginBottom: verticalScale(24),
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
  },
  tipTitle: {
    fontSize: responsiveFontSize(16),
    fontWeight: '700',
    color: '#1A211D',
    marginBottom: verticalScale(4),
  },
  tipDesc: {
    fontSize: responsiveFontSize(14),
    color: '#6B7A75',
    lineHeight: moderateScale(20),
  },
  tipImage: {
    width: scale(80),
    height: verticalScale(80),
    borderRadius: moderateScale(16),
  },
  articleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    overflow: 'hidden',
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: verticalScale(4) },
  },
  articleImage: {
    width: '100%',
    height: verticalScale(160),
  },
  articleContent: {
    padding: moderateScale(20),
  },
  articleTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: '700',
    color: '#1A211D',
    flex: 1,
    marginRight: scale(16),
  },
  articleDesc: {
    fontSize: responsiveFontSize(14),
    color: '#6B7A75',
    lineHeight: moderateScale(22),
    marginTop: verticalScale(8),
  },
  bottomTabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: verticalScale(12),
    paddingBottom: verticalScale(32),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: moderateScale(32),
    borderTopRightRadius: moderateScale(32),
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: verticalScale(-5) },
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  tabButton: {
    alignItems: 'center',
    gap: 4,
  },
  tabIconContainer: {
    padding: moderateScale(10),
    borderRadius: moderateScale(16),
  },
  tabIconActive: {
    backgroundColor: '#EDF6F1',
  },
  tabLabel: {
    fontSize: responsiveFontSize(10),
    fontWeight: '600',
    color: '#6B7A75',
    letterSpacing: 0.5,
  },
  tabLabelActive: {
    color: '#126027',
    fontWeight: '800',
  },
  pageTitle: {
    fontSize: responsiveFontSize(32),
    fontWeight: '800',
    color: '#1A211D',
  },
  pageSubtitle: {
    fontSize: responsiveFontSize(16),
    color: '#6B7A75',
    marginTop: verticalScale(4),
  },
  habitSquareCard: {
    width: scale(140),
    minHeight: 210,
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(24),
    padding: moderateScale(16),
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#126027',
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  habitIconWrap: {
    width: scale(44),
    height: verticalScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: '#EDF6F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(12),
  },
  habitTopText: {
    fontSize: responsiveFontSize(14),
    fontWeight: '700',
    color: '#1A211D',
    textAlign: 'center',
    marginBottom: verticalScale(4),
    minHeight: 40,
  },
  habitMetaText: {
    fontSize: responsiveFontSize(12),
    color: '#6B7A75',
    marginBottom: verticalScale(16),
  },
  habitSquareBtn: {
    backgroundColor: '#126027',
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(20),
    borderRadius: moderateScale(16),
    width: '100%',
    alignItems: 'center',
  },
  habitSquareBtnText: {
    color: '#FFF',
    fontSize: responsiveFontSize(12),
    fontWeight: '700',
  },
  activeDot: {
    width: scale(8),
    height: verticalScale(8),
    borderRadius: moderateScale(4),
    backgroundColor: '#4ADE80',
    marginRight: scale(6),
  },
  habitActiveText: {
    color: '#126027',
    fontSize: responsiveFontSize(12),
    fontWeight: '800',
  },
  featuredProgramCard: {
    width: '100%',
    minHeight: verticalScale(300),
    aspectRatio: 0.85,
    maxHeight: verticalScale(420),
    borderRadius: moderateScale(24),
    overflow: 'hidden',
    justifyContent: 'flex-end',
    marginBottom: verticalScale(24),
  },
  featuredProgramOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(18, 96, 39, 0.4)',
  },
  featuredProgramContent: {
    padding: moderateScale(24),
  },
  tagDark: { backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: scale(12), paddingVertical: verticalScale(6), borderRadius: moderateScale(12) },
  tagDarkText: { color: '#FFF', fontSize: responsiveFontSize(10), fontWeight: '800', letterSpacing: 1 },
  tagLight: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: scale(12), paddingVertical: verticalScale(6), borderRadius: moderateScale(12) },
  tagLightText: { color: '#FFF', fontSize: responsiveFontSize(10), fontWeight: '800', letterSpacing: 1 },
  featuredProgramTitle: { fontSize: responsiveFontSize(24), fontWeight: '800', color: '#FFF', marginBottom: verticalScale(8), lineHeight: moderateScale(30) },
  featuredProgramDesc: { fontSize: responsiveFontSize(15), color: 'rgba(255,255,255,0.8)', marginBottom: verticalScale(20), lineHeight: moderateScale(22) },
  featuredProgramBtn: { backgroundColor: '#126027', paddingVertical: verticalScale(14), borderRadius: moderateScale(16), alignItems: 'center' },
  featuredProgramBtnText: { color: '#FFF', fontSize: responsiveFontSize(14), fontWeight: '800', letterSpacing: 1 },
  featuredGlassBar: { backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: moderateScale(16), padding: moderateScale(16), marginBottom: verticalScale(16) },
  progressLabelLight: { color: '#FFF', fontSize: responsiveFontSize(10), fontWeight: '700', letterSpacing: 1 },
  progressTrackLight: { backgroundColor: 'rgba(255,255,255,0.3)', height: verticalScale(6), borderRadius: moderateScale(3), marginTop: verticalScale(8) },
  progressFillLight: { backgroundColor: '#FFF', height: verticalScale(6), borderRadius: moderateScale(3) },
  taskCard: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: moderateScale(20), padding: moderateScale(12), marginBottom: verticalScale(16), alignItems: 'center' },
  taskCardImg: { width: scale(80), height: verticalScale(80), borderRadius: moderateScale(14) },
  taskCardBody: { flex: 1, paddingLeft: scale(16) },
  taskMetaLabel: { fontSize: responsiveFontSize(10), fontWeight: '800', color: '#4ADE80', letterSpacing: 1 },
  taskMetaValue: { fontSize: responsiveFontSize(10), fontWeight: '800', color: '#6B7A75' },
  taskCardTitle: { fontSize: responsiveFontSize(16), fontWeight: '700', color: '#1A211D', marginVertical: verticalScale(6) },
  taskActionBtn: { backgroundColor: '#F0F5F2', paddingVertical: verticalScale(8), borderRadius: moderateScale(12), alignItems: 'center', marginTop: verticalScale(12) },
  taskActionBtnText: { color: '#126027', fontSize: responsiveFontSize(12), fontWeight: '800' },
  nftPromoCard: { backgroundColor: '#126027', borderRadius: moderateScale(24), padding: moderateScale(20), marginTop: verticalScale(16) },
  welcomeLabelLight: { fontSize: responsiveFontSize(10), fontWeight: '800', color: '#4ADE80', letterSpacing: 1.5, marginBottom: verticalScale(8) },
  nftPromoTitle: { fontSize: responsiveFontSize(24), fontWeight: '800', color: '#FFF', marginBottom: verticalScale(8) },
  nftPromoDesc: { fontSize: responsiveFontSize(14), color: 'rgba(255,255,255,0.8)', lineHeight: moderateScale(20) },
  nftAvatar: { width: scale(28), height: verticalScale(28), borderRadius: moderateScale(14), borderWidth: 2, borderColor: '#126027', alignItems: 'center', justifyContent: 'center' },
  nftAvatarText: { fontSize: responsiveFontSize(11), fontWeight: '900' },
  availablePointsCard: { backgroundColor: '#126027', padding: moderateScale(24), borderRadius: moderateScale(24), marginTop: verticalScale(16) },
  pointsLabel: { color: '#4ADE80', fontSize: responsiveFontSize(12), fontWeight: '800', letterSpacing: 1, marginBottom: verticalScale(12) },
  pointsBigValue: { color: '#FFF', fontSize: responsiveFontSize(48), fontWeight: '800' },
  pointsUnit: { color: 'rgba(255,255,255,0.7)', fontSize: responsiveFontSize(18), fontWeight: '600' },
  pointsBtnPrimary: { backgroundColor: '#FFF', paddingVertical: verticalScale(12), paddingHorizontal: scale(20), borderRadius: moderateScale(16) },
  pointsBtnPrimaryText: { color: '#126027', fontSize: responsiveFontSize(14), fontWeight: '800' },
  pointsBtnSecondary: { backgroundColor: 'rgba(255,255,255,0.2)', paddingVertical: verticalScale(12), paddingHorizontal: scale(20), borderRadius: moderateScale(16) },
  pointsBtnSecondaryText: { color: '#FFF', fontSize: responsiveFontSize(14), fontWeight: '800' },
  taskMetaValueDark: { fontSize: responsiveFontSize(12), fontWeight: '800', color: '#126027' },
  carbonOffsetCard: { backgroundColor: '#FFF', borderRadius: moderateScale(24), padding: moderateScale(20), flexDirection: 'row', alignItems: 'center', marginTop: verticalScale(16) },
  carbonIconWrap: { width: scale(50), height: verticalScale(50), borderRadius: moderateScale(25), backgroundColor: '#EDF6F1', alignItems: 'center', justifyContent: 'center', marginRight: scale(16) },
  carbonValueDark: { fontSize: responsiveFontSize(16), fontWeight: '800', color: '#126027' },
  badgeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginTop: verticalScale(16) },
  badgeCircleDark: { width: scale(80), height: verticalScale(80), borderRadius: moderateScale(40), backgroundColor: '#126027', alignItems: 'center', justifyContent: 'center', marginBottom: verticalScale(12) },
  badgeCircleMedium: { width: scale(80), height: verticalScale(80), borderRadius: moderateScale(40), backgroundColor: '#4ADE80', alignItems: 'center', justifyContent: 'center', marginBottom: verticalScale(12) },
  badgeCircleLight: { width: scale(80), height: verticalScale(80), borderRadius: moderateScale(40), backgroundColor: '#F0F5F2', alignItems: 'center', justifyContent: 'center', marginBottom: verticalScale(12) },
  badgeCircleLightGreen: { width: scale(40), height: verticalScale(40), borderRadius: moderateScale(20), backgroundColor: '#4ADE80', alignItems: 'center', justifyContent: 'center', marginBottom: verticalScale(12) },
  badgeTagGold: { position: 'absolute', bottom: verticalScale(-10), backgroundColor: '#F59E0B', paddingHorizontal: scale(10), paddingVertical: verticalScale(4), borderRadius: moderateScale(10), borderWidth: 2, borderColor: '#FFF' },
  badgeTagGoldText: { color: '#FFF', fontSize: responsiveFontSize(9), fontWeight: '800', letterSpacing: 1 },
  badgeTitle: { fontSize: responsiveFontSize(14), fontWeight: '800', color: '#1A211D', textAlign: 'center', marginBottom: verticalScale(4) },
  badgeTitleLight: { fontSize: responsiveFontSize(14), fontWeight: '800', color: '#6B7A75', textAlign: 'center', marginBottom: verticalScale(4) },
  badgeDesc: { fontSize: responsiveFontSize(12), color: '#6B7A75', textAlign: 'center' },
  lockedRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  lockedText: { fontSize: responsiveFontSize(10), fontWeight: '800', color: '#126027', letterSpacing: 1 },
  nftPromoCardLight: { backgroundColor: '#FFF', borderRadius: moderateScale(24), padding: moderateScale(16), flexDirection: 'row', alignItems: 'center', marginTop: verticalScale(24) },
  nftPromoLightImg: { width: scale(80), height: verticalScale(80), borderRadius: moderateScale(16), marginRight: scale(16) },
  nftPromoTitleDark: { fontSize: responsiveFontSize(18), fontWeight: '800', color: '#1A211D', marginBottom: verticalScale(4) },
  nftPromoDescDark: { fontSize: responsiveFontSize(12), color: '#6B7A75', lineHeight: moderateScale(18) },
  metaTextSmall: { fontSize: responsiveFontSize(12), color: '#6B7A75', marginTop: verticalScale(8) },
  metaTextSmallDark: { fontSize: responsiveFontSize(12), color: '#6B7A75', lineHeight: moderateScale(18) },
  metaTextWhite: { fontSize: responsiveFontSize(12), color: '#FFF', fontWeight: '600' },
  knowledgePointsCard: { backgroundColor: '#F59E0B', borderRadius: moderateScale(20), padding: moderateScale(20), flexDirection: 'row', alignItems: 'center', marginTop: verticalScale(24) },
  knowledgeIconWrap: { width: scale(44), height: verticalScale(44), borderRadius: moderateScale(22), backgroundColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center', marginRight: scale(16) },
  knowledgePointsLabel: { fontSize: responsiveFontSize(10), color: 'rgba(255,255,255,0.8)', fontWeight: '800', letterSpacing: 1 },
  knowledgePointsValue: { fontSize: responsiveFontSize(24), color: '#FFF', fontWeight: '800' },
  categoryLargeCard: { width: '100%', minHeight: verticalScale(160), aspectRatio: 2.0, maxHeight: verticalScale(240), borderRadius: moderateScale(24), overflow: 'hidden', justifyContent: 'flex-end', marginTop: verticalScale(16), marginBottom: verticalScale(16) },
  categoryLargeOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(26, 33, 29, 0.5)' },
  categoryLargeTitle: { fontSize: responsiveFontSize(20), fontWeight: '800', color: '#FFF', marginBottom: verticalScale(4) },
  categoryLargeDesc: { fontSize: responsiveFontSize(14), color: 'rgba(255,255,255,0.8)', marginBottom: verticalScale(16) },
  categoryMediumCard: { backgroundColor: '#126027', borderRadius: moderateScale(24), padding: moderateScale(24), marginBottom: verticalScale(16) },
  categoryMediumTitle: { fontSize: responsiveFontSize(18), fontWeight: '800', color: '#FFF', marginBottom: verticalScale(8) },
  categoryMediumDesc: { fontSize: responsiveFontSize(14), color: 'rgba(255,255,255,0.8)', marginBottom: verticalScale(16), lineHeight: moderateScale(22) },
  categoryOutlineBtn: { borderWidth: 1, borderColor: '#4ADE80', borderRadius: moderateScale(16), paddingVertical: verticalScale(12), alignItems: 'center' },
  categoryOutlineBtnText: { color: '#4ADE80', fontSize: responsiveFontSize(14), fontWeight: '800' },
  categorySmallCard: { backgroundColor: '#FFF', padding: moderateScale(16), borderRadius: moderateScale(20), marginBottom: verticalScale(12) },
  activeCourseRow: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: moderateScale(20), padding: moderateScale(12), marginBottom: verticalScale(12), alignItems: 'center' },
  courseThumb: { width: scale(60), height: verticalScale(60), borderRadius: moderateScale(12), marginRight: scale(16) },
  coursePercentText: { fontSize: responsiveFontSize(10), fontWeight: '800', color: '#6B7A75', letterSpacing: 1 },
  fullscreenOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#F7F9F7', zIndex: 100 },
  filterPillGroup: { flexDirection: 'row', backgroundColor: '#EDF6F1', borderRadius: moderateScale(20), padding: moderateScale(4) },
  filterPillActive: { flexDirection: 'row', backgroundColor: '#FFF', paddingHorizontal: scale(16), paddingVertical: verticalScale(8), borderRadius: moderateScale(16), alignItems: 'center' },
  filterPillActiveText: { color: '#1A211D', fontSize: responsiveFontSize(12), fontWeight: '700' },
  filterPillInactive: { flexDirection: 'row', paddingHorizontal: scale(16), paddingVertical: verticalScale(8), borderRadius: moderateScale(16), alignItems: 'center' },
  filterPillInactiveText: { color: '#6B7A75', fontSize: responsiveFontSize(12), fontWeight: '600' },
  categoryPillActive: { backgroundColor: '#126027', paddingHorizontal: scale(20), paddingVertical: verticalScale(10), borderRadius: moderateScale(20) },
  categoryPillActiveText: { color: '#FFF', fontSize: responsiveFontSize(14), fontWeight: '700' },
  categoryPillInactive: { backgroundColor: '#FFF', paddingHorizontal: scale(20), paddingVertical: verticalScale(10), borderRadius: moderateScale(20) },
  categoryPillInactiveText: { color: '#6B7A75', fontSize: responsiveFontSize(14), fontWeight: '600' },
  eventFeaturedCard: { width: '100%', minHeight: verticalScale(280), aspectRatio: 0.9, maxHeight: verticalScale(400), borderRadius: moderateScale(24), overflow: 'hidden', justifyContent: 'flex-end', marginBottom: verticalScale(24) },
  eventFeaturedOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(26, 33, 29, 0.4)' },
  eventJoinBtnInfo: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: scale(16), paddingVertical: verticalScale(12), borderRadius: moderateScale(16) },
  eventJoinBtnInfoText: { color: '#FFF', fontSize: responsiveFontSize(14), fontWeight: '800' },
  eventListCard: { backgroundColor: '#FFF', borderRadius: moderateScale(24), overflow: 'hidden', marginBottom: verticalScale(20) },
  eventListImg: { width: '100%', height: verticalScale(160) },
  dateTagRight: { position: 'absolute', right: scale(16), top: verticalScale(16), backgroundColor: '#FFF', paddingHorizontal: scale(12), paddingVertical: verticalScale(8), borderRadius: moderateScale(12) },
  dateTagRightText: { color: '#1A211D', fontSize: responsiveFontSize(12), fontWeight: '800', letterSpacing: 1 },
  eventListBody: { padding: moderateScale(20) },
  quickJoinBtn: { backgroundColor: '#EDF6F1', paddingVertical: verticalScale(12), borderRadius: moderateScale(16), alignItems: 'center' },
  quickJoinBtnText: { color: '#126027', fontSize: responsiveFontSize(14), fontWeight: '800' },
  circularAddBtn: { width: scale(44), height: verticalScale(44), borderRadius: moderateScale(22), backgroundColor: '#126027', alignItems: 'center', justifyContent: 'center' },
  leaderboardFilterRow: { flexDirection: 'row', backgroundColor: '#EDF6F1', borderRadius: moderateScale(20), padding: moderateScale(4), marginTop: verticalScale(16) },
  leaderboardTop3: { flexDirection: 'row', justifyContent: 'space-between', marginTop: verticalScale(32), paddingHorizontal: scale(16) },
  lbTopCard: { alignItems: 'center', width: '30%' },
  lbAvatarWrap: { marginBottom: verticalScale(12), alignItems: 'center' },
  lbAvatarImg: { width: scale(64), height: verticalScale(64), borderRadius: moderateScale(32), borderWidth: 3, borderColor: '#FFF' },
  lbAvatarText: { fontSize: responsiveFontSize(26), fontWeight: '900' },
  lbAvatarTextLarge: { fontSize: responsiveFontSize(32), fontWeight: '900' },
  lbRankBadge: { position: 'absolute', bottom: verticalScale(-8), width: scale(24), height: verticalScale(24), borderRadius: moderateScale(12), alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#FFF' },
  lbRankText: { color: '#FFF', fontSize: responsiveFontSize(12), fontWeight: 'bold' },
  lbTopName: { fontSize: responsiveFontSize(16), fontWeight: '700', color: '#1A211D', marginBottom: verticalScale(4) },
  lbTopPoints: { fontSize: responsiveFontSize(14), fontWeight: '600', color: '#6B7A75' },
  lbListRow: { flexDirection: 'row', backgroundColor: '#FFF', alignItems: 'center', padding: moderateScale(12), borderRadius: moderateScale(20), marginBottom: verticalScale(8) },
  lbListRank: { width: scale(30), fontSize: responsiveFontSize(16), fontWeight: '800', color: '#6B7A75', textAlign: 'center' },
  lbListAvatar: { width: scale(40), height: verticalScale(40), borderRadius: moderateScale(20) },
  lbListAvatarText: { fontSize: responsiveFontSize(16), fontWeight: '900' },
  lbListPoints: { fontSize: responsiveFontSize(14), fontWeight: '800', color: '#126027' },
  lbCurrentUserCard: { flexDirection: 'row', backgroundColor: '#126027', alignItems: 'center', padding: moderateScale(16), borderRadius: moderateScale(24), position: 'absolute', bottom: verticalScale(32), left: scale(24), right: scale(24), shadowColor: '#126027', shadowOpacity: 0.2, shadowRadius: 10 },
  lbCurrentUserAvatar: { backgroundColor: '#ECFAEF' },
  lbCurrentUserAvatarText: { color: '#126027', fontSize: responsiveFontSize(16), fontWeight: '900' },
  chatBubble: {
    padding: moderateScale(16),
    borderRadius: moderateScale(20),
    marginBottom: verticalScale(12),
    maxWidth: '85%',
  },
  chatBubbleBot: {
    backgroundColor: '#FFF',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: moderateScale(4),
  },
  chatBubbleUser: {
    backgroundColor: '#126027',
    alignSelf: 'flex-end',
    borderBottomRightRadius: moderateScale(4),
  },
  chatBubbleTextBot: {
    color: '#1A211D',
    fontSize: responsiveFontSize(14),
    lineHeight: moderateScale(22),
  },
  chatBubbleTextUser: {
    color: '#FFF',
    fontSize: responsiveFontSize(14),
    lineHeight: moderateScale(22),
  },
  chatTimeBot: {
    fontSize: responsiveFontSize(10),
    color: '#6B7A75',
    marginTop: verticalScale(8),
    alignSelf: 'flex-end',
  },
  chatTimeUser: {
    fontSize: responsiveFontSize(10),
    color: 'rgba(255,255,255,0.7)',
    marginTop: verticalScale(8),
    alignSelf: 'flex-end',
  },
  chatInput: {
    flex: 1,
    minHeight: verticalScale(48),
    backgroundColor: '#F7F9F7',
    borderRadius: moderateScale(24),
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(8),
    fontSize: responsiveFontSize(14),
    color: '#1A211D',
  },
});
