import { Platform, StyleSheet } from 'react-native';
import { ecoTheme } from '../../shared/theme/ecoTheme';

export const styles = StyleSheet.create({
  onbGlassCard: {
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    overflow: 'hidden',
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  onbEcoBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    shadowColor: ecoTheme.colors.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  onbTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFF',
    marginBottom: 16,
    textAlign: 'center',
  },
  onbDescription: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    lineHeight: 24,
  },
  onbBtn: {
    width: '100%',
    borderRadius: 100,
    overflow: 'hidden',
    shadowColor: ecoTheme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  onbGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 32,
  },
  onbBtnTxt: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
  },
  actionHost: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  actionOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(6, 27, 23, 0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  actionOverlayCard: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 30,
    paddingHorizontal: 24,
    paddingVertical: 28,
    backgroundColor: 'rgba(8, 35, 30, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#0E6D60',
    shadowOpacity: 0.28,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 16,
  },
  actionOverlayLogoWrap: {
    alignItems: 'center',
    marginBottom: 18,
  },
  actionOverlaySpinnerShell: {
    width: 132,
    height: 132,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionOverlaySpinnerRing: {
    position: 'absolute',
    width: 132,
    height: 132,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: 'rgba(207,255,234,0.22)',
    alignItems: 'center',
  },
  actionOverlaySpinnerDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    marginTop: 9,
    backgroundColor: '#B4FBE0',
    shadowColor: '#B4FBE0',
    shadowOpacity: 0.72,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  actionOverlayLogoCore: {
    width: 98,
    height: 98,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 88, 76, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#18A176',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  actionOverlayTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
    color: '#F2FFF8',
    textAlign: 'center',
  },
  actionOverlayCopy: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 21,
    color: 'rgba(227,255,244,0.76)',
    textAlign: 'center',
  },
  centeredScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    overflow: 'hidden',
  },
  bootBackdropOrb: {
    position: 'absolute',
    top: -70,
    right: -35,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(115, 255, 206, 0.12)',
  },
  bootBackdropOrbSecondary: {
    position: 'absolute',
    bottom: -110,
    left: -70,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  bootOrbitalRing: {
    position: 'absolute',
    width: 216,
    height: 216,
    borderRadius: 108,
    borderWidth: 1,
    borderColor: 'rgba(204,255,235,0.22)',
    alignItems: 'center',
  },
  bootOrbitalDot: {
    position: 'absolute',
    top: 12,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#C9FFE8',
    shadowColor: '#9FF7D4',
    shadowOpacity: 0.8,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
  },
  bootCenterpiece: {
    width: 216,
    height: 216,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  bootLogoModern: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderRadius: 28,
    backgroundColor: 'rgba(4, 27, 21, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    shadowColor: '#72F1C1',
    shadowOpacity: 0.38,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 16 },
    elevation: 15,
  },
  bootTitleModern: {
    fontSize: 24,
    fontWeight: '900',
    color: '#ECFDF5',
    letterSpacing: 0.3,
  },
  bootSubtitleModern: {
    marginTop: 10,
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(225,255,245,0.82)',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  bootLoaderChip: {
    marginTop: 28,
    minHeight: 46,
    borderRadius: 23,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  bootLoaderText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E9FFF5',
  },
  landingScreen: {
    flex: 1,
    overflow: 'hidden',
  },
  landingBackdropOrbPrimary: {
    position: 'absolute',
    top: -80,
    right: -50,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(206, 255, 233, 0.14)',
  },
  landingBackdropOrbSecondary: {
    position: 'absolute',
    bottom: -110,
    left: -60,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  launchBackdropCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  launchBackdropCore: {
    width: 150,
    height: 150,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#93FFD2',
    shadowOpacity: 0.2,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  launchBackdropCopy: {
    marginTop: 22,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: '#F1FFF8',
    textAlign: 'center',
  },
  landingShell: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  landingContent: {
    borderRadius: 38,
    paddingHorizontal: 24,
    paddingVertical: 26,
    backgroundColor: 'rgba(7, 32, 28, 0.26)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  landingBadge: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  landingBadgeText: {
    color: '#F5FFF9',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  landingVisual: {
    height: 276,
    marginTop: 22,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  landingOrbitalRing: {
    position: 'absolute',
    width: 208,
    height: 208,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: 'rgba(213,255,236,0.22)',
    alignItems: 'center',
  },
  landingOrbitalDot: {
    width: 16,
    height: 16,
    borderRadius: 999,
    marginTop: 9,
    backgroundColor: '#D5FFEC',
    shadowColor: '#D5FFEC',
    shadowOpacity: 0.76,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  landingLogoCoreShell: {
    width: 156,
    height: 156,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    shadowColor: '#9DF4CA',
    shadowOpacity: 0.2,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  landingStatCard: {
    position: 'absolute',
    width: 126,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#F4FFF9',
    shadowColor: '#042821',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  landingStatLeft: {
    left: 0,
    top: 38,
  },
  landingStatRight: {
    right: 0,
    bottom: 28,
  },
  landingStatTitle: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  landingStatValue: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    color: ecoTheme.colors.textSoft,
  },
  landingTitle: {
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '900',
    color: '#F7FFF9',
    textAlign: 'center',
  },
  landingCopy: {
    marginTop: 14,
    fontSize: 16,
    lineHeight: 25,
    color: 'rgba(239,255,247,0.84)',
    textAlign: 'center',
  },
  landingFeatureList: {
    marginTop: 22,
    gap: 12,
  },
  landingFeaturePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  landingFeatureIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  landingFeatureTextWrap: {
    flex: 1,
  },
  landingFeatureTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#F7FFF9',
  },
  landingFeatureSubtitle: {
    marginTop: 2,
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(235,255,244,0.72)',
  },
  landingActions: {
    marginTop: 24,
    gap: 12,
  },
  landingFootnote: {
    marginTop: 16,
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(229,255,240,0.62)',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: '#0D4238',
  },
  onboardingBackdropImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.34,
  },
  onboardingBackdropTint: {
    ...StyleSheet.absoluteFillObject,
  },
  onboardingBackdropOrbTop: {
    position: 'absolute',
    top: -54,
    right: -28,
    width: 232,
    height: 232,
    borderRadius: 116,
    backgroundColor: 'rgba(218,255,185,0.18)',
  },
  onboardingBackdropOrbBottom: {
    position: 'absolute',
    bottom: -88,
    left: -62,
    width: 258,
    height: 258,
    borderRadius: 129,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  onboardingBackdropLeafRight: {
    position: 'absolute',
    right: -12,
    top: 158,
    transform: [{ rotate: '8deg' }],
  },
  onboardingBackdropLeafLeft: {
    position: 'absolute',
    left: -12,
    bottom: 74,
    transform: [{ rotate: '-18deg' }],
  },
  onboardingBackdropLeafTop: {
    position: 'absolute',
    top: 56,
    left: 18,
    transform: [{ rotate: '-12deg' }],
  },
  onboardingShell: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },
  onboardingCard: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    borderRadius: 36,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 20,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1.2,
    borderColor: 'rgba(255,255,255,0.32)',
    shadowColor: '#063D2E',
    shadowOpacity: 0.30,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 18 },
    elevation: 18,
    overflow: 'hidden',
  },
  onboardingCardCompact: {
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  onboardingGlassLayer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 36,
  },
  onboardingCardTint: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 36,
  },
  onboardingGlassShine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
  },
  onboardingGlassShimmer: {
    position: 'absolute',
    top: -40,
    left: -40,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  onboardingFrostEdge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 36,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  onboardingCardGlow: {
    position: 'absolute',
    top: '30%',
    alignSelf: 'center',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(200,255,175,0.12)',
  },
  onboardingCardContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  onboardingBrandRow: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  onboardingBrandImage: {
    width: 130,
    height: 82,
  },
  onboardingBrandImageCompact: {
    width: 108,
    height: 68,
  },
  onboardingHeroWrap: {
    marginTop: 4,
    marginBottom: 8,
  },
  onboardingHeroWrapCompact: {
    marginTop: 0,
    marginBottom: 2,
  },
  onboardingStepContent: {
    flex: 1,
    width: '100%',
  },
  onboardingStepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 2,
  },
  onboardingStepEyebrowGlass: {
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  onboardingStepEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: 'rgba(12, 71, 59, 0.78)',
  },
  onboardingStepCounter: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  onboardingStepCounterText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    color: '#134B3F',
  },
  onboardingShowcaseWrap: {
    width: '100%',
    minHeight: 286,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingShowcaseWrapCompact: {
    minHeight: 228,
  },
  onboardingHeroChip: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 42,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#0E5A4C',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  onboardingHeroChipCompact: {
    minHeight: 38,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  onboardingHeroChipLeft: {
    top: 38,
    left: 4,
  },
  onboardingHeroChipRight: {
    top: 84,
    right: 6,
  },
  onboardingHeroChipText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#145947',
  },
  onboardingHeroMetricChip: {
    position: 'absolute',
    bottom: 22,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 176,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: '#0B5F58',
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  onboardingHeroMetricChipCompact: {
    bottom: 14,
    minWidth: 160,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  onboardingHeroMetricValue: {
    fontSize: 16,
    fontWeight: '900',
    color: '#F6FFF8',
  },
  onboardingHeroMetricLabel: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(239,255,246,0.82)',
  },
  onboardingPreviewOrb: {
    position: 'absolute',
    width: 248,
    height: 248,
    borderRadius: 124,
    backgroundColor: 'rgba(220,255,194,0.24)',
  },
  onboardingPreviewPanel: {
    width: '100%',
    borderRadius: 34,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.62)',
    backgroundColor: 'rgba(255,255,255,0.26)',
  },
  onboardingPreviewPanelCompact: {
    borderRadius: 28,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
  },
  onboardingPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    gap: 12,
  },
  onboardingPreviewStepLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: 'rgba(18, 73, 60, 0.62)',
  },
  onboardingPreviewTitle: {
    marginTop: 4,
    fontSize: 20,
    fontWeight: '900',
    color: '#143A31',
  },
  onboardingPreviewBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  onboardingPreviewFeatureStack: {
    gap: 10,
  },
  onboardingPreviewFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: 'rgba(255,255,255,0.60)',
  },
  onboardingPreviewFeatureRowCompact: {
    gap: 10,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  onboardingPreviewFeatureIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingPreviewFeatureTextWrap: {
    flex: 1,
  },
  onboardingPreviewFeatureTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#143A31',
  },
  onboardingPreviewFeatureDetail: {
    marginTop: 3,
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(20, 58, 49, 0.74)',
  },
  onboardingPreviewFooter: {
    marginTop: 14,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  onboardingPreviewFooterText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#145947',
  },
  illustrationWrap: {
    width: 320,
    height: 330,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  illustrationAura: {
    position: 'absolute',
    width: 272,
    height: 272,
    borderRadius: 136,
    backgroundColor: 'rgba(223,255,186,0.18)',
  },
  illustrationAuraSecondary: {
    position: 'absolute',
    width: 320,
    height: 228,
    borderRadius: 118,
    backgroundColor: 'rgba(244,255,239,0.20)',
    transform: [{ translateY: 18 }],
  },
  illustrationBubble: {
    position: 'absolute',
    bottom: 38,
    width: 286,
    height: 224,
    borderRadius: 118,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.46)',
  },
  illustrationGlowDotOne: {
    position: 'absolute',
    left: 54,
    top: 126,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#F7FFD4',
    shadowColor: '#F7FFD4',
    shadowOpacity: 0.7,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationGlowDotTwo: {
    position: 'absolute',
    right: 56,
    top: 152,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFF3C8',
    shadowColor: '#FFF3C8',
    shadowOpacity: 0.74,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationGlowDotThree: {
    position: 'absolute',
    right: 88,
    bottom: 76,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FBFFE5',
    shadowColor: '#FBFFE5',
    shadowOpacity: 0.74,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  illustrationDewDrop: {
    position: 'absolute',
    backgroundColor: 'rgba(255,255,255,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.46)',
  },
  illustrationDewDropOne: {
    top: 78,
    left: 56,
    width: 22,
    height: 30,
    borderRadius: 14,
  },
  illustrationDewDropTwo: {
    top: 96,
    right: 46,
    width: 16,
    height: 24,
    borderRadius: 12,
  },
  illustrationDewDropThree: {
    right: 74,
    bottom: 118,
    width: 18,
    height: 26,
    borderRadius: 13,
  },
  illustrationLeafBadge: {
    position: 'absolute',
    width: 54,
    height: 76,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.52)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D9FFCE',
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  illustrationLeafBadgeOne: {
    left: 44,
    top: 34,
  },
  illustrationLeafBadgeTwo: {
    left: 86,
    top: 10,
  },
  illustrationLeafBadgeThree: {
    left: 134,
    top: 0,
  },
  illustrationLeafBadgeFour: {
    right: 86,
    top: 14,
  },
  illustrationLeafBadgeFive: {
    right: 46,
    top: 46,
  },
  illustrationLeafVein: {
    width: 4,
    height: 44,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.62)',
  },
  illustrationStemLeft: {
    position: 'absolute',
    left: 68,
    bottom: 64,
    width: 4,
    height: 78,
    borderRadius: 999,
    backgroundColor: '#6FA863',
    transform: [{ rotate: '-12deg' }],
  },
  illustrationStemCenter: {
    position: 'absolute',
    left: 116,
    bottom: 58,
    width: 5,
    height: 94,
    borderRadius: 999,
    backgroundColor: '#73B468',
  },
  illustrationStemRight: {
    position: 'absolute',
    right: 72,
    bottom: 58,
    width: 4,
    height: 82,
    borderRadius: 999,
    backgroundColor: '#6FA863',
    transform: [{ rotate: '12deg' }],
  },
  illustrationSproutLeaf: {
    position: 'absolute',
    width: 26,
    height: 14,
    borderRadius: 999,
    backgroundColor: '#82C776',
  },
  illustrationSproutLeafLeft: {
    left: 52,
    bottom: 128,
    transform: [{ rotate: '-26deg' }],
  },
  illustrationSproutLeafRight: {
    right: 56,
    bottom: 116,
    transform: [{ rotate: '26deg' }],
  },
  illustrationFlower: {
    position: 'absolute',
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  illustrationFlowerLeft: {
    left: 30,
    bottom: 34,
  },
  illustrationFlowerCenter: {
    left: 126,
    bottom: 48,
  },
  illustrationFlowerRight: {
    right: 34,
    bottom: 32,
  },
  illustrationFlowerPetal: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 999,
  },
  illustrationFlowerPetalTop: {
    top: 0,
  },
  illustrationFlowerPetalRight: {
    right: 0,
  },
  illustrationFlowerPetalBottom: {
    bottom: 0,
  },
  illustrationFlowerPetalLeft: {
    left: 0,
  },
  illustrationFlowerCore: {
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.36)',
  },
  illustrationLeafPodLeft: {
    position: 'absolute',
    left: 18,
    bottom: 74,
    width: 76,
    height: 34,
    borderRadius: 999,
    backgroundColor: 'rgba(130, 198, 116, 0.42)',
    justifyContent: 'center',
    transform: [{ rotate: '-16deg' }],
  },
  illustrationLeafPodRight: {
    position: 'absolute',
    right: 18,
    bottom: 84,
    width: 76,
    height: 34,
    borderRadius: 999,
    backgroundColor: 'rgba(130, 198, 116, 0.38)',
    justifyContent: 'center',
    transform: [{ rotate: '18deg' }],
  },
  illustrationLeafPodInner: {
    width: 42,
    height: 18,
    borderRadius: 999,
    marginHorizontal: 14,
    backgroundColor: 'rgba(240,255,237,0.58)',
  },
  illustrationCharacter: {
    position: 'absolute',
    bottom: 62,
    width: 164,
    height: 198,
    borderRadius: 80,
    alignItems: 'center',
    paddingTop: 86,
    shadowColor: '#D7FFC3',
    shadowOpacity: 0.42,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
    elevation: 12,
  },
  illustrationCharacterGlow: {
    position: 'absolute',
    top: 10,
    left: 12,
    right: 12,
    bottom: 20,
    borderRadius: 64,
    backgroundColor: 'rgba(255,255,255,0.20)',
  },
  illustrationArm: {
    position: 'absolute',
    top: 92,
    width: 54,
    height: 58,
    borderRadius: 28,
    backgroundColor: '#B7EA8A',
  },
  illustrationArmLeft: {
    left: -18,
    transform: [{ rotate: '20deg' }],
  },
  illustrationArmRight: {
    right: -18,
    transform: [{ rotate: '-18deg' }],
  },
  illustrationLeg: {
    position: 'absolute',
    bottom: -22,
    width: 44,
    height: 56,
    borderRadius: 24,
    backgroundColor: '#8ACA6C',
  },
  illustrationLegLeft: {
    left: 34,
  },
  illustrationLegRight: {
    right: 34,
  },
  illustrationEyeRow: {
    flexDirection: 'row',
    gap: 26,
  },
  illustrationEye: {
    width: 18,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#224C37',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 4,
  },
  illustrationEyeSpark: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
  },
  illustrationSmile: {
    width: 34,
    height: 16,
    marginTop: 12,
    borderBottomWidth: 4,
    borderColor: '#2C6E46',
    borderRadius: 999,
  },
  illustrationBlush: {
    position: 'absolute',
    top: 116,
    width: 24,
    height: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 174, 146, 0.56)',
  },
  illustrationBlushLeft: {
    left: 30,
  },
  illustrationBlushRight: {
    right: 30,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 20,
  },
  logoRowHero: {
    marginBottom: 0,
    gap: 14,
  },
  logoBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DDF5E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoBadgeLight: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  logoBadgeHero: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  logoText: {
    fontSize: 22,
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
    letterSpacing: 0.4,
  },
  logoTextHero: {
    fontSize: 28,
    letterSpacing: 1.2,
  },
  logoTextLight: {
    color: '#FFFFFF',
  },
  onboardingTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: undefined }),
    textAlign: 'center',
    color: '#151A16',
    marginBottom: 6,
  },
  onboardingTitleCompact: {
    fontSize: 22,
    lineHeight: 28,
    marginBottom: 4,
  },
  onboardingCopy: {
    fontSize: 14,
    lineHeight: 21,
    color: '#21342B',
    textAlign: 'center',
    marginBottom: 8,
  },
  onboardingCopyCompact: {
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 6,
  },
  onboardingSpotlightGlass: {
    marginBottom: 10,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.30)',
  },
  onboardingSpotlightGlassCompact: {
    marginBottom: 6,
    borderRadius: 14,
  },
  onboardingSpotlightInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  onboardingSpotlightText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#145947',
  },
  onboardingBottomActions: {
    gap: 6,
  },
  onboardingExistingAccount: {
    marginTop: 4,
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  onboardingExistingAccountText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(21, 26, 22, 0.50)',
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 30,
    overflow: 'hidden',
    shadowColor: '#13917B',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonGradient: {
    minHeight: 58,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    overflow: 'hidden',
  },
  primaryButtonGlow: {
    position: 'absolute',
    width: 132,
    height: 132,
    top: -82,
    right: -18,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    overflow: 'hidden',
  },
  secondaryButtonGradient: {
    minHeight: 50,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  paginationDots: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: 6,
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(76, 117, 76, 0.22)',
  },
  dotActive: {
    width: 28,
    backgroundColor: '#72B865',
  },
  newOnboardingContainer: {
    flex: 1,
    backgroundColor: '#EBF5ED',
  },
  newOnboardingSafeArea: {
    flex: 1,
    justifyContent: 'space-between',
  },
  newOnboardingHeader: {
    alignItems: 'center',
    marginTop: 60,
    marginBottom: 20,
  },
  newOnboardingLogo: {
    width: 140,
    height: 32,
  },
  newOnboardingHeroContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: -20,
  },
  heroCircleWrapper: {
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#13917B',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  newOnboardingHeroImage: {
    width: '125%',
    height: '125%',
  },
  newOnboardingTextContainer: {
    paddingHorizontal: 30,
    alignItems: 'center',
    marginBottom: 40,
  },
  newOnboardingTitle: {
    fontWeight: '800',
    fontSize: 34,
    color: '#123D2B',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 40,
  },
  newOnboardingSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#123D2B',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 10,
  },
  newOnboardingBottom: {
    paddingHorizontal: 30,
    paddingBottom: Platform.OS === 'ios' ? 10 : 40,
  },
  newOnboardingButton: {
    backgroundColor: '#519E59',
    borderRadius: 30,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  newOnboardingButtonText: {
    fontWeight: '700',
    color: '#FFFFFF',
    fontSize: 18,
  },
  newOnboardingPagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    marginBottom: Platform.OS === 'ios' ? 10 : 0,
  },
  newOnboardingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#C8D7CD',
  },
  newOnboardingDotActive: {
    width: 24,
    backgroundColor: '#519E59',
  },
  authShell: {
    flexGrow: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  authHero: {
    paddingHorizontal: 24,
    paddingVertical: 32,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  authTitle: {
    fontSize: 34,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 12,
  },
  authSubtitle: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 24,
    color: 'rgba(255,255,255,0.88)',
  },
  authCard: {
    marginHorizontal: 18,
    marginTop: -26,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: ecoTheme.radius.xl,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E2EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  sectionHeadline: {
    fontSize: 22,
    fontWeight: '900',
    color: ecoTheme.colors.text,
    marginBottom: 10,
  },
  sectionCaption: {
    fontSize: 15,
    lineHeight: 22,
    color: ecoTheme.colors.textSoft,
  },
  quickLoginRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    marginBottom: 10,
  },
  quickPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    backgroundColor: '#F6FBF8',
    overflow: 'hidden',
  },
  quickPillActive: {
    borderColor: ecoTheme.colors.primaryDark,
    shadowColor: '#158771',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  quickPillGradient: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
  },
  quickPillText: {
    fontSize: 14,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  quickPillTextActive: {
    color: '#FFFFFF',
  },
  inputGroup: {
    marginTop: 16,
  },
  inputLabel: {
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '700',
    color: ecoTheme.colors.text,
  },
  textInput: {
    minHeight: 54,
    borderRadius: 18,
    backgroundColor: '#F7FBF8',
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    paddingHorizontal: 16,
    fontSize: 16,
    color: ecoTheme.colors.text,
  },
  authError: {
    color: '#C44536',
    fontSize: 14,
    marginTop: 12,
    marginBottom: 6,
  },
  authHintBox: {
    marginTop: 18,
    backgroundColor: '#F5FBF7',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E0EFE3',
  },
  authHintTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: ecoTheme.colors.text,
    marginBottom: 6,
  },
  authHintCopy: {
    fontSize: 13,
    color: ecoTheme.colors.textSoft,
    lineHeight: 20,
  },
  mainScrollContent: {
    paddingBottom: 110,
  },
  homeHero: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 34,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    shadowColor: '#0C5A4D',
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  homeHeroGreeting: {
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 26,
  },
  homeHeroSubcopy: {
    marginTop: 10,
    fontSize: 18,
    color: 'rgba(255,255,255,0.90)',
  },
  notificationBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    right: -3,
    top: -4,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E15A4E',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  notificationBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  contentSection: {
    paddingHorizontal: 18,
    paddingTop: 18,
    gap: 18,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  metricTile: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E3EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  metricValue: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  metricLabel: {
    marginTop: 6,
    fontSize: 14,
    color: ecoTheme.colors.textSoft,
  },
  surfaceCard: {
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: ecoTheme.radius.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E4F0E8',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  challengeFeatureCard: {
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  iconBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#E7F6EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  linkText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  challengeHeadline: {
    fontSize: 18,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  rowMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 14,
    color: ecoTheme.colors.textSoft,
  },
  progressLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  progressTrack: {
    height: 12,
    borderRadius: 8,
    backgroundColor: '#E4E9E6',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#249D7A',
  },
  horizontalList: {
    gap: 14,
    paddingRight: 8,
  },
  lessonHighlightCard: {
    width: 250,
    backgroundColor: '#FFFFFF',
    borderRadius: ecoTheme.radius.lg,
    overflow: 'hidden',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  lessonHighlightBody: {
    padding: 16,
    gap: 8,
  },
  lessonHighlightTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  lessonMedia: {
    width: '100%',
    borderRadius: 20,
    backgroundColor: '#C7E9CD',
  },
  lessonMediaFallback: {
    width: '100%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  actionCard: {
    width: '48%',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E3EFE7',
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  actionIconBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E8F6EE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  actionCardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  actionCardSubtitle: {
    marginTop: 6,
    fontSize: 14,
    color: ecoTheme.colors.textSoft,
  },
  pageHeader: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  pageHeaderTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  pageHeaderSubtitle: {
    marginTop: 8,
    fontSize: 16,
    color: 'rgba(255,255,255,0.88)',
  },
  searchField: {
    minHeight: 54,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: '#E3E9E4',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: ecoTheme.colors.text,
  },
  featuredLessonCard: {
    gap: 14,
  },
  featuredOverlay: {
    position: 'absolute',
    left: '50%',
    top: 92,
    marginLeft: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(47, 165, 95, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  courseRowCard: {
    gap: 10,
  },
  courseRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  courseRowTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  coursePercent: {
    alignSelf: 'flex-end',
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.textSoft,
  },
  habitsCard: {
    gap: 12,
    backgroundColor: '#EEF7F1',
  },
  habitRow: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  habitTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.text,
    maxWidth: 210,
  },
  pointsPill: {
    minWidth: 60,
    minHeight: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5F7EE',
    paddingHorizontal: 10,
  },
  pointsPillMuted: {
    backgroundColor: '#E4F7E9',
  },
  pointsPillText: {
    fontSize: 14,
    fontWeight: '800',
    color: ecoTheme.colors.primaryDark,
  },
  pointsEarnedText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
    textAlign: 'center',
  },
  challengeListCard: {
    padding: 14,
  },
  challengeListTop: {
    flexDirection: 'row',
    gap: 14,
  },
  miniMedia: {
    width: 100,
    height: 100,
    borderRadius: 18,
    backgroundColor: '#C9ECD0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  challengeContent: {
    flex: 1,
    gap: 8,
  },
  challengeListTitle: {
    flex: 1,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    color: ecoTheme.colors.text,
    marginRight: 10,
  },
  challengeMetaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  challengeActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  inlinePanelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 52,
    borderRadius: 22,
    backgroundColor: '#EAF8EF',
    borderWidth: 1,
    borderColor: '#DCEEDF',
  },
  inlinePanelButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  trackerHeroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trackerHeroLeft: {
    flex: 1,
    paddingRight: 14,
  },
  trackerHeroTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  trackerHeroStreak: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '900',
    color: '#111111',
    marginVertical: 8,
  },
  progressRingOuter: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 14,
    borderColor: '#D9F0DE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressRingInner: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  progressRingValue: {
    fontSize: 28,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  calendarCard: {
    gap: 16,
  },
  calendarMonth: {
    fontSize: 18,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarWeekLabel: {
    width: '14.2%',
    textAlign: 'center',
    fontSize: 14,
    color: ecoTheme.colors.textSoft,
    fontWeight: '700',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    width: '14.2%',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F7F4',
  },
  calendarBubbleActive: {
    backgroundColor: '#55B85D',
  },
  calendarBubbleToday: {
    borderWidth: 2,
    borderColor: ecoTheme.colors.primaryDark,
  },
  calendarBubbleText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.text,
  },
  calendarBubbleTextActive: {
    color: '#FFFFFF',
  },
  calendarBubblePlaceholder: {
    width: 38,
    height: 38,
  },
  checkInCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkInTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  checkInButton: {
    minWidth: 110,
  },
  profileSummaryCard: {
    gap: 16,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatarBubble: {
    backgroundColor: '#CBEFD6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontSize: 22,
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  profileName: {
    fontSize: 22,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  profilePointsPill: {
    borderRadius: 20,
    backgroundColor: '#ECFAEF',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  profilePointsText: {
    fontSize: 16,
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  profileMetric: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#F5FBF7',
    padding: 14,
    alignItems: 'center',
  },
  profileMetricValue: {
    fontSize: 20,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  profileMetricLabel: {
    marginTop: 6,
    fontSize: 13,
    color: ecoTheme.colors.textSoft,
  },
  badgeCard: {
    width: 150,
    minHeight: 180,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#31B65B',
    backgroundColor: '#FFFFFF',
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeCardFull: {
    width: '48%',
  },
  badgeCardLocked: {
    borderColor: '#B8B8B8',
    backgroundColor: '#E4E4E4',
  },
  badgeIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#EDF9F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  badgeIconWrapLocked: {
    backgroundColor: '#D2D2D2',
  },
  badgeName: {
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  badgeRequirement: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: ecoTheme.colors.textSoft,
    marginTop: 10,
  },
  logPreviewCard: {
    gap: 10,
  },
  logPoints: {
    fontSize: 15,
    fontWeight: '900',
    color: ecoTheme.colors.primaryDark,
  },
  hashText: {
    fontSize: 14,
    color: '#8A94A0',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  overlayShell: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
  },
  overlayHeader: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 28,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backLabel: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  overlayTitle: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 18,
  },
  overlaySubtitle: {
    marginTop: 8,
    fontSize: 16,
    color: 'rgba(255,255,255,0.88)',
  },
  overlayBody: {
    flex: 1,
    backgroundColor: ecoTheme.colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -12,
    overflow: 'hidden',
  },
  overlayScroll: {
    padding: 18,
    gap: 16,
  },
  assistantHero: {
    alignItems: 'center',
    paddingTop: 18,
  },
  assistantMascot: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: '#ECF8EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  assistantThread: {
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 12,
  },
  assistantBubble: {
    maxWidth: '85%',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  assistantBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#FFFFFF',
  },
  assistantBubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: '#DFF6E4',
  },
  assistantBubbleText: {
    fontSize: 18,
    lineHeight: 26,
    color: ecoTheme.colors.text,
  },
  assistantTime: {
    marginTop: 8,
    fontSize: 12,
    color: ecoTheme.colors.textSoft,
  },
  quickReplyWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 18,
    paddingBottom: 14,
  },
  quickReplyChip: {
    minHeight: 42,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: ecoTheme.colors.primary,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0FBF3',
  },
  quickReplyText: {
    fontSize: 15,
    color: ecoTheme.colors.primaryDark,
    fontWeight: '700',
  },
  assistantComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
    paddingBottom: 22,
  },
  assistantInput: {
    flex: 1,
    minHeight: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: ecoTheme.colors.outline,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    fontSize: 16,
    color: ecoTheme.colors.text,
  },
  sendButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ecoTheme.colors.primaryDark,
  },
  segmentedControl: {
    flexDirection: 'row',
    margin: 18,
    marginBottom: 0,
    backgroundColor: '#E8ECE8',
    borderRadius: 24,
    padding: 4,
  },
  segmentActive: {
    flex: 1,
    minHeight: 46,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentInactive: {
    flex: 1,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActiveText: {
    fontSize: 16,
    fontWeight: '800',
    color: ecoTheme.colors.text,
  },
  segmentInactiveText: {
    fontSize: 16,
    fontWeight: '700',
    color: ecoTheme.colors.textSoft,
  },
  eventCard: {
    gap: 12,
  },
  eventJoinButton: {
    minWidth: 110,
    flex: 0,
  },
  lessonDetailCard: {
    gap: 14,
  },
  lessonMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  lessonBodyText: {
    fontSize: 16,
    lineHeight: 26,
    color: ecoTheme.colors.text,
  },
  leaderboardCard: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  leaderboardCardActive: {
    backgroundColor: '#E8F6EE',
  },
  rankLabel: {
    width: 58,
    fontSize: 18,
    fontWeight: '900',
    color: ecoTheme.colors.text,
  },
  leaderboardName: {
    fontSize: 18,
    fontWeight: '900',
    color: ecoTheme.colors.text,
    maxWidth: 190,
  },
  badgePillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  tinyBadge: {
    minHeight: 30,
    borderRadius: 16,
    backgroundColor: '#EEF8F1',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tinyBadgeGold: {
    backgroundColor: '#F6E4A3',
  },
  tinyBadgeText: {
    fontSize: 13,
    fontWeight: '700',
    color: ecoTheme.colors.primaryDark,
  },
  tinyBadgeTextGold: {
    color: '#856400',
  },
  rewardsHeroCard: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardsHeroValue: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '900',
    color: ecoTheme.colors.primary,
  },
  badgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  achievementCard: {
    gap: 12,
  },
  timelineRail: {
    gap: 10,
  },
  timelineRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  timelineNodeWrap: {
    width: 26,
    alignItems: 'center',
  },
  timelineNode: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: ecoTheme.colors.primaryDark,
    borderWidth: 4,
    borderColor: '#D4EFE1',
    marginTop: 16,
  },
  timelineLine: {
    width: 4,
    flex: 1,
    backgroundColor: '#CFEBDD',
    minHeight: 86,
    borderRadius: 2,
  },
  timelineCard: {
    flex: 1,
    gap: 8,
    borderWidth: 1,
    borderColor: '#C3DFF5',
  },
  transparencyDetailCard: {
    gap: 10,
    borderWidth: 1,
    borderColor: '#D6EADF',
  },
  transparencyLine: {
    fontSize: 15,
    color: ecoTheme.colors.text,
  },
  bottomBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    minHeight: 78,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: '#DCE8E1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
    shadowColor: ecoTheme.colors.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  bottomBarItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  bottomBarLabel: {
    fontSize: 12,
    color: '#98A0A5',
  },
  bottomBarLabelActive: {
    color: ecoTheme.colors.primaryDark,
    fontWeight: '800',
  },
  chatbotFabOuter: {
    position: 'absolute',
    right: 20,
    bottom: 110,
    zIndex: 999,
  },
  chatbotFab: {
    shadowColor: '#10816A',
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    borderRadius: 34,
  },
  chatbotFabImg: {
    width: 68,
    height: 68,
    resizeMode: 'contain',
  },
  topNavbar: {
    paddingTop: 50,
    paddingHorizontal: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7F9F7',
  },
  topNavAvatar: {
    borderWidth: 2,
    borderColor: '#4ADE80',
  },
  topNavAvatarText: {
    fontSize: 18,
  },
  topNavTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#126027',
    letterSpacing: 2,
    flex: 1,
    textAlign: 'center',
  },
  topNavTitleDark: {
    color: '#1A211D',
  },
  topNavBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#F59E0B',
  },
  homeContent: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  welcomeLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1.5,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1A211D',
    marginTop: 4,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: '#6B7A75',
    marginTop: 4,
    marginBottom: 24,
  },
  homeMetricRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  homeMetricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  homeMetricIconWrapBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FDE68A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  homeMetricValue: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1A211D',
    marginBottom: 4,
  },
  homeMetricLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1,
  },
  weeklyGoalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  weeklyGoalLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7A75',
    letterSpacing: 1,
    marginBottom: 12,
  },
  weeklyGoalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A211D',
    marginBottom: 12,
  },
  weeklyGoalText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7A75',
  },
  publicInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  todayChallengeCard: {
    backgroundColor: '#D4F7D4',
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#4ADE80',
  },
  challengeBadge: {
    backgroundColor: '#126027',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 16,
  },
  challengeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  todayChallengeTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#126027',
    marginBottom: 8,
  },
  todayChallengeDesc: {
    fontSize: 15,
    color: '#126027',
    opacity: 0.8,
    marginBottom: 24,
  },
  challengeCompleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    borderRadius: 16,
    gap: 8,
  },
  challengeCompleteBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#126027',
  },
  dailyTipCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A211D',
    marginBottom: 4,
  },
  tipDesc: {
    fontSize: 14,
    color: '#6B7A75',
    lineHeight: 20,
  },
  tipImage: {
    width: 80,
    height: 80,
    borderRadius: 16,
  },
  articleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#126027',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
  },
  articleImage: {
    width: '100%',
    height: 160,
  },
  articleContent: {
    padding: 20,
  },
  articleTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A211D',
    flex: 1,
    marginRight: 16,
  },
  articleDesc: {
    fontSize: 14,
    color: '#6B7A75',
    lineHeight: 22,
    marginTop: 8,
  },
  bottomTabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    paddingBottom: 32,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -5 },
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  tabButton: {
    alignItems: 'center',
    gap: 4,
  },
  tabIconContainer: {
    padding: 10,
    borderRadius: 16,
  },
  tabIconActive: {
    backgroundColor: '#EDF6F1',
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6B7A75',
    letterSpacing: 0.5,
  },
  tabLabelActive: {
    color: '#126027',
    fontWeight: '800',
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1A211D',
  },
  pageSubtitle: {
    fontSize: 16,
    color: '#6B7A75',
    marginTop: 4,
  },
  habitSquareCard: {
    width: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#126027',
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  habitIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EDF6F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  habitTopText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A211D',
    textAlign: 'center',
    marginBottom: 4,
  },
  habitMetaText: {
    fontSize: 12,
    color: '#6B7A75',
    marginBottom: 16,
  },
  habitSquareBtn: {
    backgroundColor: '#126027',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
  },
  habitSquareBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4ADE80',
    marginRight: 6,
  },
  habitActiveText: {
    color: '#126027',
    fontSize: 12,
    fontWeight: '800',
  },
  featuredProgramCard: {
    width: '100%',
    height: 380,
    borderRadius: 24,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    marginBottom: 24,
  },
  featuredProgramOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(18, 96, 39, 0.4)',
  },
  featuredProgramContent: {
    padding: 24,
  },
  tagDark: { backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  tagDarkText: { color: '#FFF', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  tagLight: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  tagLightText: { color: '#FFF', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  featuredProgramTitle: { fontSize: 24, fontWeight: '800', color: '#FFF', marginBottom: 8, lineHeight: 30 },
  featuredProgramDesc: { fontSize: 15, color: 'rgba(255,255,255,0.8)', marginBottom: 20, lineHeight: 22 },
  featuredProgramBtn: { backgroundColor: '#126027', paddingVertical: 14, borderRadius: 16, alignItems: 'center' },
  featuredProgramBtnText: { color: '#FFF', fontSize: 14, fontWeight: '800', letterSpacing: 1 },
  featuredGlassBar: { backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 16, padding: 16, marginBottom: 16 },
  progressLabelLight: { color: '#FFF', fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  progressTrackLight: { backgroundColor: 'rgba(255,255,255,0.3)', height: 6, borderRadius: 3, marginTop: 8 },
  progressFillLight: { backgroundColor: '#FFF', height: 6, borderRadius: 3 },
  taskCard: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 20, padding: 12, marginBottom: 16, alignItems: 'center' },
  taskCardImg: { width: 80, height: 80, borderRadius: 14 },
  taskCardBody: { flex: 1, paddingLeft: 16 },
  taskMetaLabel: { fontSize: 10, fontWeight: '800', color: '#4ADE80', letterSpacing: 1 },
  taskMetaValue: { fontSize: 10, fontWeight: '800', color: '#6B7A75' },
  taskCardTitle: { fontSize: 16, fontWeight: '700', color: '#1A211D', marginVertical: 6 },
  taskActionBtn: { backgroundColor: '#F0F5F2', paddingVertical: 8, borderRadius: 12, alignItems: 'center', marginTop: 12 },
  taskActionBtnText: { color: '#126027', fontSize: 12, fontWeight: '800' },
  nftPromoCard: { backgroundColor: '#126027', borderRadius: 24, padding: 20, marginTop: 16 },
  welcomeLabelLight: { fontSize: 10, fontWeight: '800', color: '#4ADE80', letterSpacing: 1.5, marginBottom: 8 },
  nftPromoTitle: { fontSize: 24, fontWeight: '800', color: '#FFF', marginBottom: 8 },
  nftPromoDesc: { fontSize: 14, color: 'rgba(255,255,255,0.8)', lineHeight: 20 },
  nftAvatar: { width: 28, height: 28, borderRadius: 14, borderWidth: 2, borderColor: '#126027', alignItems: 'center', justifyContent: 'center' },
  nftAvatarText: { fontSize: 11, fontWeight: '900' },
  availablePointsCard: { backgroundColor: '#126027', padding: 24, borderRadius: 24, marginTop: 16 },
  pointsLabel: { color: '#4ADE80', fontSize: 12, fontWeight: '800', letterSpacing: 1, marginBottom: 12 },
  pointsBigValue: { color: '#FFF', fontSize: 48, fontWeight: '800' },
  pointsUnit: { color: 'rgba(255,255,255,0.7)', fontSize: 18, fontWeight: '600' },
  pointsBtnPrimary: { backgroundColor: '#FFF', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 16 },
  pointsBtnPrimaryText: { color: '#126027', fontSize: 14, fontWeight: '800' },
  pointsBtnSecondary: { backgroundColor: 'rgba(255,255,255,0.2)', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 16 },
  pointsBtnSecondaryText: { color: '#FFF', fontSize: 14, fontWeight: '800' },
  taskMetaValueDark: { fontSize: 12, fontWeight: '800', color: '#126027' },
  carbonOffsetCard: { backgroundColor: '#FFF', borderRadius: 24, padding: 20, flexDirection: 'row', alignItems: 'center', marginTop: 16 },
  carbonIconWrap: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#EDF6F1', alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  carbonValueDark: { fontSize: 16, fontWeight: '800', color: '#126027' },
  badgeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginTop: 16 },
  badgeCircleDark: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#126027', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  badgeCircleMedium: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#4ADE80', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  badgeCircleLight: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#F0F5F2', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  badgeCircleLightGreen: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#4ADE80', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  badgeTagGold: { position: 'absolute', bottom: -10, backgroundColor: '#F59E0B', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10, borderWidth: 2, borderColor: '#FFF' },
  badgeTagGoldText: { color: '#FFF', fontSize: 9, fontWeight: '800', letterSpacing: 1 },
  badgeTitle: { fontSize: 14, fontWeight: '800', color: '#1A211D', textAlign: 'center', marginBottom: 4 },
  badgeTitleLight: { fontSize: 14, fontWeight: '800', color: '#6B7A75', textAlign: 'center', marginBottom: 4 },
  badgeDesc: { fontSize: 12, color: '#6B7A75', textAlign: 'center' },
  lockedRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  lockedText: { fontSize: 10, fontWeight: '800', color: '#126027', letterSpacing: 1 },
  nftPromoCardLight: { backgroundColor: '#FFF', borderRadius: 24, padding: 16, flexDirection: 'row', alignItems: 'center', marginTop: 24 },
  nftPromoLightImg: { width: 80, height: 80, borderRadius: 16, marginRight: 16 },
  nftPromoTitleDark: { fontSize: 18, fontWeight: '800', color: '#1A211D', marginBottom: 4 },
  nftPromoDescDark: { fontSize: 12, color: '#6B7A75', lineHeight: 18 },
  metaTextSmall: { fontSize: 12, color: '#6B7A75', marginTop: 8 },
  metaTextSmallDark: { fontSize: 12, color: '#6B7A75', lineHeight: 18 },
  metaTextWhite: { fontSize: 12, color: '#FFF', fontWeight: '600' },
  knowledgePointsCard: { backgroundColor: '#F59E0B', borderRadius: 20, padding: 20, flexDirection: 'row', alignItems: 'center', marginTop: 24 },
  knowledgeIconWrap: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  knowledgePointsLabel: { fontSize: 10, color: 'rgba(255,255,255,0.8)', fontWeight: '800', letterSpacing: 1 },
  knowledgePointsValue: { fontSize: 24, color: '#FFF', fontWeight: '800' },
  categoryLargeCard: { width: '100%', height: 200, borderRadius: 24, overflow: 'hidden', justifyContent: 'flex-end', marginTop: 16, marginBottom: 16 },
  categoryLargeOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(26, 33, 29, 0.5)' },
  categoryLargeTitle: { fontSize: 20, fontWeight: '800', color: '#FFF', marginBottom: 4 },
  categoryLargeDesc: { fontSize: 14, color: 'rgba(255,255,255,0.8)', marginBottom: 16 },
  categoryMediumCard: { backgroundColor: '#126027', borderRadius: 24, padding: 24, marginBottom: 16 },
  categoryMediumTitle: { fontSize: 18, fontWeight: '800', color: '#FFF', marginBottom: 8 },
  categoryMediumDesc: { fontSize: 14, color: 'rgba(255,255,255,0.8)', marginBottom: 16, lineHeight: 22 },
  categoryOutlineBtn: { borderWidth: 1, borderColor: '#4ADE80', borderRadius: 16, paddingVertical: 12, alignItems: 'center' },
  categoryOutlineBtnText: { color: '#4ADE80', fontSize: 14, fontWeight: '800' },
  categorySmallCard: { backgroundColor: '#FFF', padding: 16, borderRadius: 20, marginBottom: 12 },
  activeCourseRow: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 20, padding: 12, marginBottom: 12, alignItems: 'center' },
  courseThumb: { width: 60, height: 60, borderRadius: 12, marginRight: 16 },
  coursePercentText: { fontSize: 10, fontWeight: '800', color: '#6B7A75', letterSpacing: 1 },
  fullscreenOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#F7F9F7', zIndex: 100 },
  filterPillGroup: { flexDirection: 'row', backgroundColor: '#EDF6F1', borderRadius: 20, padding: 4 },
  filterPillActive: { flexDirection: 'row', backgroundColor: '#FFF', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 16, alignItems: 'center' },
  filterPillActiveText: { color: '#1A211D', fontSize: 12, fontWeight: '700' },
  filterPillInactive: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 16, alignItems: 'center' },
  filterPillInactiveText: { color: '#6B7A75', fontSize: 12, fontWeight: '600' },
  categoryPillActive: { backgroundColor: '#126027', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20 },
  categoryPillActiveText: { color: '#FFF', fontSize: 14, fontWeight: '700' },
  categoryPillInactive: { backgroundColor: '#FFF', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20 },
  categoryPillInactiveText: { color: '#6B7A75', fontSize: 14, fontWeight: '600' },
  eventFeaturedCard: { width: '100%', height: 350, borderRadius: 24, overflow: 'hidden', justifyContent: 'flex-end', marginBottom: 24 },
  eventFeaturedOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(26, 33, 29, 0.4)' },
  eventJoinBtnInfo: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16 },
  eventJoinBtnInfoText: { color: '#FFF', fontSize: 14, fontWeight: '800' },
  eventListCard: { backgroundColor: '#FFF', borderRadius: 24, overflow: 'hidden', marginBottom: 20 },
  eventListImg: { width: '100%', height: 160 },
  dateTagRight: { position: 'absolute', right: 16, top: 16, backgroundColor: '#FFF', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  dateTagRightText: { color: '#1A211D', fontSize: 12, fontWeight: '800', letterSpacing: 1 },
  eventListBody: { padding: 20 },
  quickJoinBtn: { backgroundColor: '#EDF6F1', paddingVertical: 12, borderRadius: 16, alignItems: 'center' },
  quickJoinBtnText: { color: '#126027', fontSize: 14, fontWeight: '800' },
  circularAddBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#126027', alignItems: 'center', justifyContent: 'center' },
  leaderboardFilterRow: { flexDirection: 'row', backgroundColor: '#EDF6F1', borderRadius: 20, padding: 4, marginTop: 16 },
  leaderboardTop3: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 32, paddingHorizontal: 16 },
  lbTopCard: { alignItems: 'center', width: '30%' },
  lbAvatarWrap: { marginBottom: 12, alignItems: 'center' },
  lbAvatarImg: { width: 64, height: 64, borderRadius: 32, borderWidth: 3, borderColor: '#FFF' },
  lbAvatarText: { fontSize: 26, fontWeight: '900' },
  lbAvatarTextLarge: { fontSize: 32, fontWeight: '900' },
  lbRankBadge: { position: 'absolute', bottom: -8, width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#FFF' },
  lbRankText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },
  lbTopName: { fontSize: 16, fontWeight: '700', color: '#1A211D', marginBottom: 4 },
  lbTopPoints: { fontSize: 14, fontWeight: '600', color: '#6B7A75' },
  lbListRow: { flexDirection: 'row', backgroundColor: '#FFF', alignItems: 'center', padding: 12, borderRadius: 20, marginBottom: 8 },
  lbListRank: { width: 30, fontSize: 16, fontWeight: '800', color: '#6B7A75', textAlign: 'center' },
  lbListAvatar: { width: 40, height: 40, borderRadius: 20 },
  lbListAvatarText: { fontSize: 16, fontWeight: '900' },
  lbListPoints: { fontSize: 14, fontWeight: '800', color: '#126027' },
  lbCurrentUserCard: { flexDirection: 'row', backgroundColor: '#126027', alignItems: 'center', padding: 16, borderRadius: 24, position: 'absolute', bottom: 32, left: 24, right: 24, shadowColor: '#126027', shadowOpacity: 0.2, shadowRadius: 10 },
  lbCurrentUserAvatar: { backgroundColor: '#ECFAEF' },
  lbCurrentUserAvatarText: { color: '#126027', fontSize: 16, fontWeight: '900' },
  chatBubble: {
    padding: 16,
    borderRadius: 20,
    marginBottom: 12,
    maxWidth: '85%',
  },
  chatBubbleBot: {
    backgroundColor: '#FFF',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  chatBubbleUser: {
    backgroundColor: '#126027',
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  chatBubbleTextBot: {
    color: '#1A211D',
    fontSize: 14,
    lineHeight: 22,
  },
  chatBubbleTextUser: {
    color: '#FFF',
    fontSize: 14,
    lineHeight: 22,
  },
  chatTimeBot: {
    fontSize: 10,
    color: '#6B7A75',
    marginTop: 8,
    alignSelf: 'flex-end',
  },
  chatTimeUser: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 8,
    alignSelf: 'flex-end',
  },
  chatInput: {
    flex: 1,
    height: 48,
    backgroundColor: '#F7F9F7',
    borderRadius: 24,
    paddingHorizontal: 20,
    fontSize: 14,
    color: '#1A211D',
  },
});
